### ISSUE TITLE
LibsDisguise compatibility hook.

### ISSUE THREAD

**Issue by mibby** [NEZNAMY/TAB#6] opened 2019-07-30 20:48 UTC
Would it be possible to add a compatibility hook for LibsDisguise so you can still show TAB nametags above your head when you are disguised as a mob? Currently your name just turns white when disguising and back to normal when undisguising.

**Comment by NEZNAMY** [comment] 2019-07-30 20:50
Duplicate of #2

**Comment by NEZNAMY** [comment] 2019-08-15 18:23
Such a thing is not related to this plugin, nametags are shown for player entities only by default. Your disguise plugin can make custom name visible and put player's name there and modify it in some way. Other than that, it would be very complicated to actually do.
TLDR: It's not this plugin's job to modify custom names of mobs created by other plugins.

**Closed by NEZNAMY** 2019-08-15 18:23 UTC
