### ISSUE TITLE
Having space for all players the size of vanished player

### ISSUE THREAD

**Issue by TheJoshue** [NEZNAMY/TAB#478] opened 2022-01-09 14:04 UTC
**Server version**
First server:
![image](https://user-images.githubusercontent.com/56804505/148685284-37783b17-9541-4016-845c-f39d7ba16aed.png)

Second server:
![image](https://user-images.githubusercontent.com/56804505/148685305-cb2ecca0-7015-4f4e-a170-0955bef33e20.png)

**Plugin version** ("latest" is not a version)
First server:
![image](https://user-images.githubusercontent.com/56804505/148685344-c0f0c4cd-a4ef-4988-a80c-63af35588215.png)

Second server:
![image](https://user-images.githubusercontent.com/56804505/148685337-7ff40735-0d2c-4978-8789-047106d03fba.png)

**Describe the bug**
When player is in vanish (any vanish that uses ProtocolLib to hide player), player who is looking at tablist will have space even if he's the only one on the server.

**How to reproduce**
1. Have ProtocolLib, EssentialsX (for vanish) or VanishNoPacket plugin on the server.
2. Do `/v` to vanish.
3. Let someone other who don't have permission to see you check the tablist.

**Expected behavior**
There should be not space if some player is hidden (in vanish).

**Actual behavior**
Before admin vanished
![image](https://user-images.githubusercontent.com/56804505/148685504-82fc16d7-3b46-4443-a93c-ac2681c788fd.png)

After admin vanished
![image](https://user-images.githubusercontent.com/56804505/148685536-22581b14-f3ac-4c33-a523-c488c34aec99.png)

**Additional info** (errors, screenshots, ...)
Used the latest recommended build of ProtocolLib plugin for 1.8-1.17 from official jenkins server of ProtocolLib's developer
![image](https://user-images.githubusercontent.com/56804505/148685456-e4274340-e050-4936-8b32-11fd6049af09.png)

I have TAB's `tablist-name-formatting.align-tabsuffix-on-the-right` config option set to `true`.

**Comment by Tanguygab** [comment] 2022-01-09 14:05
duplicate of #347

**Closed by Tanguygab** 2022-01-09 14:05 UTC

**Comment by TheJoshue** [comment] 2022-01-09 14:09
> duplicate of #347

so, this means that only way to prevent this will be disabling `align-tabsuffix-on-the-right` option?

**Comment by NEZNAMY** [comment] 2022-01-09 14:10
Yes until it's implemented.
