### ISSUE TITLE
unlimited-nametag-prefix-suffix-mode for bungeecord

### ISSUE THREAD

**Issue by Heliosard** [NEZNAMY/TAB#143] opened 2020-04-23 10:15 UTC
The `unlimited-nametag-prefix-suffix-mode' feature is very interesting in my opinion to display useful information like the player's life, ping, etc. But it is also very useful for purely cosmetic purposes. Displaying the Title of the player, his Guild or other above his head in "abovename" is very nice.

Unfortunately, this function is not available in bungeecord mode. Can you add it?

Thanks for your help,

**Comment by NEZNAMY** [comment] 2020-04-23 10:46
It cannot be added to bungeecord directly as it's missing necessary packets and events.

**Comment by Heliosard** [comment] 2020-04-23 16:33
In bungee mode, we have the plugin on both the bukkit and the bungee. The function is already available in bukkit mode. Why not make the function available in bridge mode?

**Comment by mashmarvin** [comment] 2020-04-23 18:05
Or you could put Bungee Side an option "bungee-bridge-mode" which means, all the config on Bungee gets transferred to Bukkit. You cant use Global Playerlist then, but its simpler for end-user than copying config and reload on every server

**Comment by golfmaichai1** [comment] 2020-11-09 10:00
USE MYSQL DATA

**Comment by Tanguygab** [comment] 2020-11-09 10:11
1. that's not what the issue is about
2. MySQL support has already been requested in another issue #17

**Closed** 2022-03-04 22:10 UTC
Labels: Feature request
