### ISSUE TITLE
[Velocity] [MySQL] Failed to connect to MySQL

### ISSUE THREAD

**Issue by axctal** [NEZNAMY/TAB#1268] opened 2024-04-13 03:09 UTC
### Server version

velocity-3.3.0-SNAPSHOT-376

### TAB version

4.1.2

### Stack trace

[19:51:17 WARN] [tab]: §cFailed to connect to MySQL
[19:51:17 WARN] [tab]: §cjava.lang.ClassNotFoundException: com.mysql.jdbc.Driver
[19:51:17 WARN] [tab]: §c       at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass0(PluginClassLoader.java:87)
[19:51:17 WARN] [tab]: §c       at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:64)
[19:51:17 WARN] [tab]: §c       at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
[19:51:17 WARN] [tab]: §c       at java.base/java.lang.Class.forName0(Native Method)
[19:51:17 WARN] [tab]: §c       at java.base/java.lang.Class.forName(Class.java:375)
[19:51:17 WARN] [tab]: §c       at me.neznamy.tab.shared.config.Configs.<init>(Configs.java:76)
[19:51:17 WARN] [tab]: §c       at me.neznamy.tab.shared.TAB.load(TAB.java:163)
[19:51:17 WARN] [tab]: §c       at me.neznamy.tab.shared.TAB.create(TAB.java:112)
[19:51:17 WARN] [tab]: §c       at me.neznamy.tab.platforms.velocity.VelocityTAB.onProxyInitialization(VelocityTAB.java:53)
[19:51:17 WARN] [tab]: §c       at me.neznamy.tab.platforms.velocity.Lmbda$3.execute(Unknown Source)
[19:51:17 WARN] [tab]: §c       at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56)
[19:51:17 WARN] [tab]: §c       at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598)
[19:51:17 WARN] [tab]: §c       at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479)
[19:51:17 WARN] [tab]: §c       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[19:51:17 WARN] [tab]: §c       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[19:51:17 WARN] [tab]: §c       at java.base/java.lang.Thread.run(Thread.java:840)

### Steps to reproduce (if known)

Install TAB on velocity proxy server
Configure MySQL settings in 'config.yml'
Start proxy, get error

### Additional info

MySQL = MariaDB v 10.6.14 , on it's own server ( separate from proxy, minecraft backends or standalone minecraft server(s) )
Java = openjdk 17.0.10_p7
PaperMC 1.20.1 on standalone and backend servers

TAB-Bridge v5.0.4 on backend servers, however, error exists regardless of backend server(s) status ( including all of them being off )

I tried TAB one version down ( v4.0.9 ) as well as a "standard Java" -- got exactly same behavior.

TAB on Velocity is working fine, as long as you do not enable MySQL ...

Other plugins are connecting to this database server just fine.
Those "working well" plugins include :
Same TAB plugin (same version) but from standalone PaperMC server or backend servers
LuckPerms from standalone PaperMC
LuckPerms from the very velocity proxy server on which TAB is failing.    <<<< !!!!
GriefProtection
BedWars
Minepacks

... the point is -- DB server is OK, as it is working for other plugins from a variety of servers, including the velocity proxy ( on which TAB is having issues ) // I do know how to set firewall properly, create and set grants for user(s) / database(s)

In MySQL logs :
<date> [Warning] Aborted connection 48 to db: 'unconnected' user: 'unauthenticated' host: '<hostname>' (This connection closed normally without authentication)

I double-checked grants on DB for this 'user'@'%.<stuff>' - all looks OK ( besides, as I said, same TAB connects to the same DB under the same credentials )

I also experimented with config - enclosing username / password in a single quotes ( ' ), as well as tried the 'useSSL' options both ways ( true / false ) --- got exactly same results.

Should you need any more data - will be glad to assist.

Thank you

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Tanguygab** [comment] 2024-04-13 08:21
duplicate of #1128

**Comment by NEZNAMY** [comment] 2024-09-01 07:45
https://github.com/NEZNAMY/TAB/wiki/MySQL#availability will not be added. You don't need MySQL support on proxy anyway, as TAB on proxy already has everything on the same place.

**Closed by NEZNAMY** 2024-09-01 07:45 UTC
Labels: Type: Error
