### ISSUE TITLE
The "Network Protocol Error" problem still present on ReplayMod

### ISSUE THREAD

**Issue by SundayMC** [NEZNAMY/TAB#1341] opened 2024-07-26 12:28 UTC
### TAB version

4.1.6

### Software causing compatibility issue

ReplayMod 1.20.6-2.6.18

### Additional info

The kick bug for “Network Protocol Error” that had been patched for clients in 4.1.6, however affect replaymod files (you get instantly kicked from the replay for the same scoreboard issue).

As a result, all replays recorded on servers with TAB in 1.20.6+ are corrupted...

### Checklist

- [X] I am running latest version of the plugin
- [ ] I ticked all of the boxes without actually reading them
- [X] The compatibility wiki page does not mention this incompatibility
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment] 2024-07-26 12:48
How is this a TAB issue? What does the mod do? Replicate all packets? Does that include scoreboards? If yes, double registering will obviously cause this. What error was shown in the client?

**Comment by SundayMC** [comment] 2024-07-26 15:24
From what I've seen [here](https://github.com/ReplayMod/ReplayMod/blob/stable/src/main/java/com/replaymod/recording/packet/PacketListener.java), it does seem that ReplayMod works by listening/retranscribing all packets (but I'm not sure).

However, from what I could quickly see, ReplayMod doesn't seem to add a second recording layer for scoreboards (wso there's not necessarily redundancy).

And finally, here's the error returned in the client console: 
```
[Render thread/ERROR]: Failed to handle packet net.minecraft.class_2751@6e081c48
java.lang.IllegalArgumentException: An objective with the name 'TAB-BelowName' already exists!
	at net.minecraft.class_269.method_1168(class_269.java:51) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_11144(class_634.java:1943) ~[client-intermediary.jar:?]
	at net.minecraft.class_2751.method_11838(class_2751.java:71) ~[client-intermediary.jar:?]
	at net.minecraft.class_2751.method_11054(class_2751.java:17) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:25) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:162) [client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:136) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:121) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1275) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:888) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:265) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.15.11.jar:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:586) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
```

**Comment by NEZNAMY** [comment] 2024-07-26 15:26
The fastest solution would be to ask the developer if the plugin resend scoreboard packets as well, because if it does, it makes sense you ran into this issue. TAB has several layers of checks to make sure this does not happen on its own, which you also confirmed by saying it only happens when adding the mod.

**Comment by NEZNAMY** [comment] 2024-08-17 07:36
Any news @SundayMC ?

**Comment by NEZNAMY** [comment] 2024-08-25 10:43
@SundayMC if you do not respond, issue will be closed as caused by another plugin.

**Comment by LindaJuffermans** [comment] 2024-08-28 16:50
Hi, I'm one of the staff members of ReplayMod support.

ReplayMod records the network packets that the client receives from the Minecraft server and stores those in the recording.
When the recording is being replayed, a virtual server is created that sends the packets to the client and lets the Minecraft client handle them.

If the client received scoreboard packets, they are also stored and then resent to the client on playback.

I hope this helps.

**Comment by NEZNAMY** [comment] 2024-08-28 16:52
Then the answer is clear. Replay mod has sent scoreboard packets while player still had TAB's packets active, causing double register. There is absolutely no kind of malfunction on TAB's end.

**Comment by LindaJuffermans** [comment] 2024-08-28 17:10
Can you clarify what you mean with "has TAB's packets active"? Why are they active, shouldn't they be processed the same way they were originally processed at recording time?

**Comment by NEZNAMY** [comment] 2024-08-28 17:13
Does player's scoreboard view get reset when replay starts? If not, there are still objectives registered from before and registering them again will result in this.

**Comment by NEZNAMY** [comment] 2024-09-06 07:20
Any news @LindaJuffermans ?

**Comment by LindaJuffermans** [comment] 2024-09-08 16:04
Yes, our developer has found the problem in the ReplayMod code which is used to cut recordings into smaller snippets.
Should be an updated release out this week.

**Comment by NEZNAMY** [comment] 2024-09-08 16:05
So can this issue be closed as caused by another software?

**Closed** 2024-09-08 16:54 UTC
Labels: Resolution: Caused by another software, Type: Compatibility issue
