### ISSUE TITLE
Empty spaces in players list

### ISSUE THREAD

**Issue by LeoPotter** [NEZNAMY/TAB#65] opened 2019-11-16 17:53 UTC
Hi, for me and for me other players would be very incredible if you added the possibility to create empty spaces in players list, like, there are 5 players in the server who are using 5 spaces but not all, with this function, plus them there be also all other players spaces used by empty name spaces. I hope you'll understand what I'm saying.

**Comment by NEZNAMY** [comment] 2019-11-16 17:56
How is this not duplicate of #31 ?

**Comment by LeoPotter** [comment] 2019-11-16 18:01
> 
> 
> How is this not duplicate of #31 ?

This is not, I just want all online players in the first avable spaces and then all empty spaces, not that suddivision.

**Comment by NEZNAMY** [comment] 2019-11-30 14:27
Are you able to provide a screenshot of what you want it to look like ?

**Comment by LeoPotter** [comment] 2019-11-30 14:46
> 
> 
> Are you able to provide a screenshot of what you want it to look like ?

The bloomed are are players: https://i.imgur.com/8v7rHDJ.png

**Comment by NEZNAMY** [comment] 2019-11-30 15:41
Organizing player list using fake player slots. Just like #31 says.

**Comment by NEZNAMY** [comment] 2019-12-05 13:49
Request is matching #31 's title - Add option to have fake player slots for organizing player list

**Closed by NEZNAMY** 2019-12-05 13:49 UTC
Labels: Duplicate, Feature request

**Comment by Tanguygab** [comment] 2020-09-23 11:53
![](https://github.trello.services/images/mini-trello-icon.png) [Organized PlayerList](https://trello.com/c/cAkIgMhZ/2-organized-playerlist)

**Comment by Tanguygab** [comment] 2020-09-23 11:53
![](https://github.trello.services/images/mini-trello-icon.png) [Organized PlayerList](https://trello.com/c/cAkIgMhZ/2-organized-playerlist)
