### ISSUE TITLE
Velocity kick on /btab reload

### ISSUE THREAD

**Issue by sl0wl0r1s** [NEZNAMY/TAB#1187] opened 2023-12-26 22:09 UTC
### Server version

Velocity 3.3.0 and purpur-1.20.2-2095

### TAB version

TAB.v4.1.2 & TAB-Bridge.v5.0.1

### Describe the bug

Hello everyone,
I'm using the TAB plugin with the TAB-Bridge dependency for my velocity based network and Purpur in the backends.
When the player enters I immediately notice from the backend server console this message "[TAB-Bridge] Blocked attempt to add player sl0wl0r1s into team 60F124E4_Z10" which is repeated endlessly and is sometimes also followed by alerts where TAB-Bridge tells me which takes many ms to receive the value of the placeholders.
I also notice that the player prefix and the name start flashing if you look at the tab, changing color to white without the prefix.
I don't notice any alerts from the Velocity console, but I noticed something rather strange; if I try to carry out the /Btab Reload command, ALL players are kicked from the network receiving the message "Recived unexpected null component" and in the console I find many errors like "Skipped plugin message send to sl0wl0r1s, because player is not connected to any server " which do not stop repeating themselves until the player logs in, logs out and logs back into the server.
I also tried to debug and I'll leave the results in the pastebin.
Sorry for my english btw im italian, I await your news and thank you regardless for the work done.

### Expected behavior

The plugin should not give errors and should be able to communicate with velocity, but in particular it should not kick everyone when reloading and should not give delays in loading the placeholders.

### Steps to reproduce

1 Install latest Velocity;
2 Install latest 1.20 Purpur;
3 Install latest TAB in the proxy;
4 Install latest TAB-Bridge in the backends;
5 Add some placeholders like luckperms and statistics in the tab and scoreboard. 

### Additional info

https://pastebin.com/bpDH7z5X
![Screenshot 2023-12-26 230007](https://github.com/NEZNAMY/TAB/assets/116310867/a6417e2f-0f95-4436-a92d-5547263cb6d8)
![Screenshot 2023-12-26 230121](https://github.com/NEZNAMY/TAB/assets/116310867/7964c02e-6688-4f14-b5eb-8cc99920145f)
![Screenshot 2023-12-26 230144](https://github.com/NEZNAMY/TAB/assets/116310867/d56bfff1-832e-4085-b1cc-3af753ec47e2)
![Screenshot 2023-12-26 225115](https://github.com/NEZNAMY/TAB/assets/116310867/8dd48b6b-027d-4bff-9d3b-8c232acdf870)
![Screenshot 2023-12-26 225959](https://github.com/NEZNAMY/TAB/assets/116310867/f45dce31-5bbd-4b5e-a11b-d5f2dde44dfe)

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by loris-slow** [comment] 2023-12-26 22:10
Idk if u can read pastebin so i post even the screen of the pastebin.
![Screenshot 2023-12-26 231018](https://github.com/NEZNAMY/TAB/assets/116310867/b88027d6-3b4a-4032-845d-e0f4557988f1)
![Screenshot 2023-12-26 230954](https://github.com/NEZNAMY/TAB/assets/116310867/cd554d39-4f40-4f21-b727-8550689260c3)
![Screenshot 2023-12-26 230958](https://github.com/NEZNAMY/TAB/assets/116310867/025aaaf1-d0f3-444e-a0c3-39af214cab98)
![Screenshot 2023-12-26 231003](https://github.com/NEZNAMY/TAB/assets/116310867/c225af09-642f-45fe-a9e7-f0aaacffb3ff)

**Comment by loris-slow** [comment] 2023-12-26 22:11
Sorry for closing, my bad.

**Comment by NEZNAMY** [comment] 2023-12-26 22:16
The reason for bridge saying "blocked attempt.." is because another plugin tried to break TAB. I am assuming you want the plugin to work, otherwise you would not be installing it. Same with tablist formatting, except it cannot be trigger based, but as a repeating task, which means another plugin can change tablist formatting and TAB will shortly after fix it. None of these 2 "problems" are actually issues in the plugin, assuming it doesn't happen without other plugins.

Regarding the kick, I will need more information about reproducing the issue. For example, try without any other backend/proxy plugins and if it persists, disable features one by one until it stops to find out which one is causing it.

**Comment by sl0wl0r1s** [comment] 2023-12-26 22:19
Thanks for your immediate response.
I already tried with another proxy and none of these problems arose.
Since I've been using Velocity I have these problems.
I have already tried removing each Velocity feature one at a time but all the above problems continue to appear.

**Comment by sl0wl0r1s** [comment] 2023-12-26 22:19
> The reason for bridge saying "blocked attempt.." is because another plugin tried to break TAB. I am assuming you want the plugin to work, otherwise you would not be installing it. Same with tablist formatting, except it cannot be trigger based, but as a repeating task, which means another plugin can change tablist formatting and TAB will shortly after fix it. None of these 2 "problems" are actually issues in the plugin, assuming it doesn't happen without other plugins.
> 
> Regarding the kick, I will need more information about reproducing the issue. For example, try without any other backend/proxy plugins and if it persists, disable features one by one until it stops to find out which one is causing it.

Thanks for your immediate response.
I already tried with another proxy and none of these problems arose.
Since I've been using Velocity I have these problems.
I have already tried removing each Velocity feature one at a time but all the above problems continue to appear.

**Comment by NEZNAMY** [comment] 2023-12-26 22:20
So it works fine on BungeeCord? And you definitely did not disable all TAB features if it continues. Did you remove all other plugins too?

**Comment by sl0wl0r1s** [comment] 2023-12-26 22:24
> So it works fine on BungeeCord? And you definitely did not disable all TAB features if it continues. Did you remove all other plugins too?

I'm sorry, I didn't understand you meant the TAB features, I thought you were talking about the Velocity features, now I'll try immediately and let you know.
I tried FlameCord which is a fork of Waterfall and it works without any problems.
As for the plugins, the only one that could modify the tab is CMI and I have already tried to disable it but nothing.

**Comment by NEZNAMY** [comment] 2023-12-26 22:25
Rather than guessing which plugin it is, remove them all to be sure. They may be modifying packets and you don't even know.

**Comment by sl0wl0r1s** [comment] 2023-12-26 22:33
> Rather than guessing which plugin it is, remove them all to be sure. They may be modifying packets and you don't even know.

Ok I tried one by one to disable the TAB features and the problems are not resolved.
Now I'll try to start the server without any plugin and let you know.

**Comment by sl0wl0r1s** [comment] 2023-12-26 22:41
Here I am again, by deleting all the plugins the tab problem no longer occurs, so I assume there is a plugin that is causing this and I will try to understand which one it is so as to let you know as soon as possible.
However, the problem of all players kicking when I reload still occurs.

**Comment by NEZNAMY** [comment] 2023-12-26 22:46
You don't need to let me know which plugin is trying to break TAB, since I cannot do anything about it.
Regarding the kick issue, can you try to set up a test network and reproduce it there with minimal setup? Including default config, since I don't believe placeholders are causing this. I will try to reproduce it using provided steps tomorrow, however, I don't have any expectations, because if it was that easy to reproduce, you would not be the only person in the world having this issue.

**Comment by sl0wl0r1s** [comment] 2023-12-26 22:56
> You don't need to let me know which plugin is trying to break TAB, since I cannot do anything about it. Regarding the kick issue, can you try to set up a test network and reproduce it there with minimal setup? Including default config, since I don't believe placeholders are causing this. I will try to reproduce it using provided steps tomorrow, however, I don't have any expectations, because if it was that easy to reproduce, you would not be the only person in the world having this issue.

I have already tried to reproduce the problem with a basic setup and the kick problem occurs.
I understand what you're telling me, but if it works perfectly with one proxy and not with another, it makes me think that there is a problem either in the proxy or in the plugin.
But according to what the wiki stated, the proxy appears to be supported, and that's why I'm asking you for support.

**Comment by sl0wl0r1s** [comment] 2023-12-26 23:12
I just want to let you know that the message "Skipped plugin message send to sl0wl0r1s, because player is not connected to any server (message= Expansionplaceholder_time[00:11:43 / 12:11 AM])" also appears when a player from hub moves to the various backends.

**Comment by NEZNAMY** [comment] 2023-12-26 23:18
I am aware of this message, you can ignore it. I will try to reproduce it with the steps you provided tomorrow. In the meantime, it would be amazing if you made a minimalistic setup that reproduces it and then uploaded it somewhere and I would try it.

**Comment by sl0wl0r1s** [comment] 2023-12-26 23:20
> I am aware of this message, you can ignore it. I will try to reproduce it with the steps you provided tomorrow. In the meantime, it would be amazing if you made a minimalistic setup that reproduces it and then uploaded it somewhere and I would try it.

See you tomorrow.

**Comment by NEZNAMY** [comment] 2023-12-27 10:58
The kick is caused by calling `com.velocitypowered.api.proxy.player.TabListEntry.setDisplayName(@Nullable Component displayName)` with `null` component.

The issue was introduced in build 304. I checked both commits for this build and actual code for setting display name, unfortunately, I didn't find anything wrong. You will need to wait for Velocity developers to fix this.

**Closed** 2023-12-27 11:41 UTC
Labels: Type: Bug, Resolution: Out of scope

**Comment by sl0wl0r1s** [comment] 2023-12-28 16:39
> Has been fixed: https://github.com/PaperMC/Velocity/commit/00ef92bc5c82c46ed4770aaaf126c285a6ab705c

Ty to everyone!!
