### ISSUE TITLE
Layout and Groups on TAB not sorting correctly

### ISSUE THREAD

**Issue by Tariq1235** [NEZNAMY/TAB#1085] opened 2023-09-25 03:53 UTC
### Server version

1.19.2

### TAB version

4.0.4

### Describe the bug

The Plugin isnt doing a proper layout and it isnt sorting groups properly. Im not sure if it is colliding with another plugin or the configuration is incorrect.
![2023-09-23_21 09 04](https://github.com/NEZNAMY/TAB/assets/76603754/f2e7a7c1-6220-4331-88f0-fc2b61eb77de)

That photo shows what it is currently looking like, all out of order

### Expected behavior

I want the layout to be sorted correctly and also all of my ranks to be sorted under the correct area.

### Steps to reproduce

The Config:
https://gyazo.com/2de86d34e3eac0588331542e2a7e9f36
The Groups:
https://gyazo.com/fe31143f76def82fd24bd2b939ee8cff

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment] 2023-09-25 05:58
Did you [check if player version was detected correctly](https://github.com/NEZNAMY/TAB/wiki/Additional-information#detection-1)?

**Comment by NEZNAMY** [comment] 2023-10-01 14:45
Did you die @Tariq1235 ? You did not respond for a week.

**Comment by Tariq1235** [comment] 2023-10-01 22:11
Ive been busy, sorry about that @NEZNAMY  and Thank you !

**Comment by NEZNAMY** [comment] 2023-10-01 22:21
Did you check the guide? Do you have VV on bungeecord? Did you resolve it?

**Comment by NEZNAMY** [comment] 2023-10-05 16:51
@Tariq1235 I will close this issue if you don't respond.

**Comment by NEZNAMY** [comment] 2023-10-08 08:33
Assuming user has died, as well as the cause being VV on BungeeCord.

**Closed by NEZNAMY** 2023-10-08 08:33 UTC
Labels: Type: Bug, Resolution: Caused by another plugin
