### ISSUE TITLE
[Feature Request] mspt

### ISSUE THREAD

**Issue by Titaniumtown** [NEZNAMY/TAB#193] opened 2020-08-04 19:55 UTC
can you add a mspt option?

**Comment by NEZNAMY** [comment] 2020-08-04 19:55
What is that?

**Comment by Titaniumtown** [comment] 2020-08-04 19:56
milliseconds per tick

**Comment by NEZNAMY** [comment] 2020-08-04 19:57
Try to request it for PlaceholderAPI. I have no idea how to get the value.

**Comment by Titaniumtown** [comment] 2020-08-04 19:57
i have no idea what that is.

**Comment by NEZNAMY** [comment] 2020-08-04 19:58
A plugin dedicated to creating placeholders you can use in plugins https://www.spigotmc.org/resources/placeholderapi.6245/

**Comment by AryToNeX** [comment] 2020-08-28 15:55
This is how PaperSpigot implements MSPT.
https://github.com/PaperMC/Paper/blob/master/Spigot-Server-Patches/0437-Add-tick-times-API-and-mspt-command.patch

Calculating an average MSPT should be as simple as getting the average TPS value and dividing 1000 (ms) by that value

1 second / 20 ticks = 50 ms (the ideal MSPT) so we can assume that anything higher than 50 ms is lag and anything below 50 ms is (too) fast.

**Comment by Titaniumtown** [comment] 2020-08-28 15:58
> This is how PaperSpigot implements MSPT.
> https://github.com/PaperMC/Paper/blob/master/Spigot-Server-Patches/0437-Add-tick-times-API-and-mspt-command.patch
> 
> Calculating an average MSPT should be as simple as getting the average TPS value and dividing 1000 (ms) by that value
> 
> 1 second / 20 ticks = 50 ms (the ideal MSPT) so we can assume that anything higher than 50 ms is lag and anything below 50 ms is (too) fast.

I was thinking something like that, but I don't know that much about how you would implement it (nor do I know java) to make an informed comment on how @NEZNAMY about how to implement it.

**Comment by AryToNeX** [comment] 2020-08-28 16:08
> I don't know that much about how you would implement it

What about something like this?
```java
Placeholders.registerPlaceholder(new ServerPlaceholder("%mspt%", 1000) {
	public String get() {
		try {
			// We get the TPS value the same way as the %tps% placeholder
			Object nmsServer = Bukkit.getServer().getClass().getMethod("getServer").invoke(Bukkit.getServer());
			double value = ((double[]) nmsServer.getClass().getField("recentTps").get(nmsServer))[0];
			double tps = Math.min(20, value);
			// Instead of returning the TPS value, we divide 1000 (ms) by that value
			return 1000 / tps;
		} catch (Throwable t) {
			return "-1";
		}
	}
});
```

**Comment by NEZNAMY** [comment] 2020-08-28 16:10
The problem is that this will show no less than 50, even if ticks take less time to process. The point of this variable would be to see how close are you to reach 50, which you will not find out.

**Comment by AryToNeX** [comment] 2020-08-28 16:11
@NEZNAMY yes... what about now?

**Comment by NEZNAMY** [comment] 2020-08-28 16:13
I have no idea, which is why I did not add it yet. Also check #200 , I edited my message.

**Comment by NEZNAMY** [comment] 2020-09-06 19:30
I have no idea how to do this, it would also be a better idea to recommend to some PlaceholderAPI expansion (such as server). Closing until I get more people who really want this and don't want to use placeholderapi.

**Closed by NEZNAMY** 2020-09-06 19:30 UTC
Labels: Feature request, Help wanted
