### ISSUE TITLE
Plugin is breaks after some time

### ISSUE THREAD

**Issue by BakiDance** [NEZNAMY/TAB#1092] opened 2023-10-04 00:36 UTC
### Server version

Paper 1.20.1 & Waterfall #544

### TAB version

4.0.6

### Describe the bug

I'm not sure how to appropriately address this bug. The plugin appears to work as expected after starting the server, however, after some time, placeholders, RGB, formatting, animations, and cross-server listings break. Overall, it seems like the TAB stops updating, as new players who join lack formatting completely.

I'm using TAB 4.0.6 on Waterfall #544, with TAB Bridge 3.1.6 on all of my Paper 1.20.1 servers.

----

I've recorded a video of this happening here: https://youtu.be/-VPa9H-fLp4
This is just after I had logged into the server, my player formatting does not apply and players within other servers on the network do not show up until after I reload the plugin. (My broken nametag does get left behind after reloading, however according to others, I do have a working nametag that works as expected after the plugin is reloaded.)

/btab debug reports that the specified player is not loaded. After reloading the plugin, the debug command works and shows the following:

![image](https://github.com/NEZNAMY/TAB/assets/43658058/bda3f794-7a60-48de-bb06-f833604bbef5)

Occasionally, while the TAB is broken, I will see this appear in Bungee's console:
```
[00:22:58 WARN] [TAB]: Placeholder %luckperms_last_group_on_tracks_level% used in sorting type PLACEHOLDER_HIGH_TO_LOW returned "" for player Zenf00, which is not a valid number.
```
However, these placeholders DO parse when run in the backend server (eg. /papi parse Zenf00 %luckperms_last_group_on_tracks_level%), and work as expected after reloading TAB.

----
I've attached my error log files. Both files are about 2MB, and only contain a few seconds of data
[errors.log](https://github.com/NEZNAMY/TAB/files/12798071/errors.log)
[placeholder-errors.log](https://github.com/NEZNAMY/TAB/files/12798072/placeholder-errors.log)

### Expected behavior

Check the video; the "expected" behavior appears after a manual reload.

### Steps to reproduce

As far as I can tell, wait until additional players start joining and the plugin will break.

### Additional info

This issue may be related to #1090, however I'm experiencing a lot more than just placeholders breaking. If need be, I can upload my entire TAB folder.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment] 2023-10-04 06:04
Error file did not show full stack trace. Add `-XX:-OmitStackTraceInFastThrow` into your startup flags. Then, restart and delete error log. If you get it again (you probably will), send it.

**Comment by BakiDance** [comment] 2023-10-05 02:33
[errors.log](https://github.com/NEZNAMY/TAB/files/12811694/errors.log)

**Comment by NEZNAMY** [comment] 2023-10-05 06:30
This was already fixed in a newer bungeecord build.

**Comment by MineTommy** [comment] 2023-10-05 12:38
Is this Fixed in Waterfall 545? Currently we have the Same Issues. Running with Waterfall 544

**Comment by NEZNAMY** [comment] 2023-10-05 12:39
I am not reponsible for development of bungeecord forks and I don't track it either. Find out and see, or go back to bungeecord.

**Comment by MineTommy** [comment] 2023-10-05 12:48
Okay Thanks Neznamy

**Comment by BakiDance** [comment] 2023-10-05 19:12
> This was already fixed in a newer bungeecord build.

Which build, exactly, was the one which fixed it? It would be easier for me to report this to Waterfall with that information.

**Comment by BakiDance** [comment] 2023-10-05 21:13
Thanks. But I don't use Bungeecord and don't plan on switching. Could you give more information on what was fixed, if not a build number? I'm not sure what in particular md5 said is fixed. A Github issue would be useful in reporting this issue to Paper.

**Comment by NEZNAMY** [comment] 2023-10-05 21:25
The error you sent was fixed. I don't know the exact build number, but latest should work.

**Comment by NEZNAMY** [comment] 2023-10-06 09:42
@BakiDance try new build from actions.

**Comment by MineTommy** [comment] 2023-10-08 08:53
Its not fixed with official BungeeCord Build

https://laby.net/post/bQBzmCTF
BungeeCord 1756

**Comment by NEZNAMY** [comment] 2023-10-08 08:54
> Its not fixed with official BungeeCord Build
> 
> https://laby.net/post/bQBzmCTF BungeeCord 1756

TAB version?

**Comment by MineTommy** [comment] 2023-10-08 08:57
4.0.6
TabBridge 3.1.6

10:56:41 [INFO] MineTommy executed command: /btab cpu
10:56:41 [WARNING] Error in dispatching command
java.lang.NullPointerException

No errors before in the Console

**Comment by NEZNAMY** [comment] 2023-10-08 08:59
> 4.0.6 TabBridge 3.1.6
> 
> 10:56:41 [INFO] MineTommy executed command: /btab cpu 10:56:41 [WARNING] Error in dispatching command java.lang.NullPointerException
> 
> No errors before in the Console

Read the message above your first message.

**Comment by MineTommy** [comment] 2023-10-08 09:00
No Last Entry 2.10.2023

**Comment by NEZNAMY** [comment] 2023-10-08 09:01
How big is the error file?

**Comment by MineTommy** [comment] 2023-10-08 09:03
976KB
For the Startup Flag i need to Restart the Proxy. I have now 24 Players online.
I can Restart first next night
But i have deleted now the Error.log
Maybe on the Next Crash we found the Error

**Comment by NEZNAMY** [comment] 2023-10-08 09:04
1MB limit https://github.com/NEZNAMY/TAB/issues/1090#issuecomment-1747287804

**Comment by MineTommy** [comment] 2023-10-08 09:06
08.10.2023 - 11:03:38 - [TAB v4.0.6] An error was thrown when executing task
08.10.2023 - 11:03:38 - java.lang.NullPointerException: null
08.10.2023 - 11:03:45 - [TAB v4.0.6] An error was thrown when executing task
08.10.2023 - 11:03:45 - java.lang.NullPointerException: null

This  are the First Errors. I think i need to Restart the Proxy but not now

**Comment by NEZNAMY** [comment] 2023-10-08 09:06
You need to both add the startup flag and update TAB.

**Comment by MineTommy** [comment] 2023-10-08 09:08
Update TAB? 4.06 is the Last Version!

**Comment by NEZNAMY** [comment] 2023-10-08 09:08
Once again, read the message above your first message.

**Comment by MineTommy** [comment] 2023-10-08 09:10
Sorryyy to early in the Morning

Do you have an Paypal link for me. This Great support i need to Support

**Comment by NEZNAMY** [comment] 2023-10-08 09:11
No. Also this is not support, this is fixing a bug.

**Comment by MineTommy** [comment] 2023-10-08 09:17
Okay i have Update to Last Build
Now we need to wait. But sure. You Plugin is Great. I want to Support you

Do you have an Discord.

**Comment by NEZNAMY** [comment] 2023-10-08 09:18
There is no discord for the public.

**Comment by MineTommy** [comment] 2023-10-08 11:06
Same with Snapshop
[errors.log](https://github.com/NEZNAMY/TAB/files/12840452/errors.log)

**Comment by NEZNAMY** [comment] 2023-10-08 11:08
Try build 871.

**Comment by NEZNAMY** [comment] 2023-10-08 11:09
Try build 872 (once it compiles).

**Comment by MineTommy** [comment] 2023-10-08 11:09
Okay then this. Night. Now i have 35 Players

**Comment by MineTommy** [comment] 2023-10-11 07:06
Is fixed
Thank you (Works also with current Waterfall)

**Comment by BakiDance** [comment] 2023-10-11 20:46
![image](https://github.com/NEZNAMY/TAB/assets/43658058/c58e7512-9951-48d9-aea5-5e98171d5f79)
![2023-10-11_15 44 10](https://github.com/NEZNAMY/TAB/assets/43658058/7b24172a-c591-41ed-ad26-aaa08a675a50)

Placeholders still break on #875 on Bungeecord.

**Comment by NEZNAMY** [comment] 2023-10-11 20:53
Did you get error file in TAB's folder? Can you show output of `/btab debug <player>`? Do the placeholders parse in `/btab parse <player> <placeholder>?

**Comment by BakiDance** [comment] 2023-10-11 22:53
[errors.log](https://github.com/NEZNAMY/TAB/files/12875263/errors.log)
![2023-10-11_17 50 49](https://github.com/NEZNAMY/TAB/assets/43658058/978416e1-0fd8-4ba1-9584-9b6611c42760)

(Ran `/btab debug` on Takorot, and it showed "Disconnected". All other players were connected.)
![image](https://github.com/NEZNAMY/TAB/assets/43658058/81f547ac-da94-4931-a2ed-4b9fc238f692)

(Placeholders do not parse for Takorot using `/btab parse <player> <placeholder>`, but they do for other players.)
![image](https://github.com/NEZNAMY/TAB/assets/43658058/eba89671-ec2e-41d8-a601-7273c3994f27)

As before, reloading the plugin "fixes" the issue.

**Comment by BakiDance** [comment] 2023-10-11 22:54
![2023-10-11_17 54 21](https://github.com/NEZNAMY/TAB/assets/43658058/1085ade8-d9a6-4d9a-8e75-870f0c7f2f1d)

How the TAB *should* look, right after a `/btab reload`.

**Comment by NEZNAMY** [comment] 2023-10-12 07:34
Try new build.

**Comment by BakiDance** [comment] 2023-10-14 00:09
Trying #878. Still receiving previous issue.
![2023-10-13_14 41 43](https://github.com/NEZNAMY/TAB/assets/43658058/094c31c3-a3cc-423a-8b8c-8a102777101c)
![2023-10-13_14 41 15](https://github.com/NEZNAMY/TAB/assets/43658058/f1bac4a7-76b4-4ae7-8c4c-f43b046faabc)

An error.log was not generated

**Comment by NEZNAMY** [comment] 2023-10-14 06:29
You'll need to find a way to reproduce it.

**Comment by BakiDance** [comment] 2023-10-14 10:57
Still do not have a new error file to attach.

**Comment by NEZNAMY** [comment] 2023-10-14 10:59
Someone ran into this issue as well, in their case players are not connected with bridge properly on join, because for some reason the plugin message doesn't make it from backend to the proxy. Reload fixes it. Is this your case as well? You can check `/btab debug <player>` to see if player is connected or not.

**Comment by BakiDance** [comment] 2023-10-14 11:22
Yes, that does seem to describe the problem. It doesn't happen with every
join, and I haven't figured out how to reproduce it. It seems to happen
fairly often though, and I haven't had this issue before 1.20.2.

If there's anything I can provide, please let me know.

**Comment by NEZNAMY** [comment] 2023-10-14 11:25
You can try to find steps to reproduce it in a testing environment.

**Comment by NEZNAMY** [comment] 2023-10-14 19:59
@BakiDance update bridge to 3.1.7.

**Comment by BakiDance** [comment] 2023-10-15 19:32
That seems to have fixed it. :) Thank you so much for the help.

**Closed** 2023-10-16 19:24 UTC
Labels: Type: Bug, Resolution: Added / Fixed
