### ISSUE TITLE
Instead of based on groups the plugin should be based on permissions

### ISSUE THREAD

**Issue by Sm4k1na** [NEZNAMY/TAB#81] opened 2019-12-23 18:29 UTC
I always used pex for permissions so this plugin was perfect, but now I use AquaCore and The plugin doesn't seems to find the player's group so it doesn't work.
My idea was to add an option like orHasPermission: ""
And if that permissions is true then the player has that tab group.

**Comment by NEZNAMY** [comment] 2019-12-23 18:38
Basically what i said in #42 .

**Comment by Sm4k1na** [comment] 2019-12-24 17:05
I am just saying to check if a player has tab.group.Owner then he will have Owner in tab and  in the tag,
If a player has more tab.group.groups then you give him the most important. That's it, so that all permission plugin will be compatible

**Comment by NEZNAMY** [comment] 2019-12-24 19:25
Yes, exactly, permission-based group assigned just like i explained in #42

**Comment by Sm4k1na** [comment] 2019-12-24 19:27
I didn't get what you said in that thread so it is added and it's just tab. group. group name or you didn't add it yet?

**Comment by NEZNAMY** [comment] 2019-12-24 19:29
Permission-based group assignment using "tab.group.<group name>" permission. This is not done yet, but a config option to enable this will be added.

**Comment by Sm4k1na** [comment] 2019-12-24 19:30
Nice thanks

**Comment by NEZNAMY** [comment] 2020-01-22 17:07
Duplicate of #42

**Closed by NEZNAMY** 2020-01-22 17:07 UTC
Labels: Duplicate, Feature request
