### ISSUE TITLE
Memory leak during worlds unloading

### ISSUE THREAD

**Issue by gamerover98** [NEZNAMY/TAB#320] opened 2021-06-06 00:37 UTC
**Server version**
1.12.2 but this doesn't matter.

**Plugin version** ("latest" is not a version)
2.8.10

**Describe the bug**

As an example, in the class NameTag, you have a field called "collision". This field is a Map that has been implemented as an **Hash**Map. 

Normally, the key class, have to override the equals(...) and hashCode() methods that may be used to have the uniqueness of the instance, like a String object.

I suggest you read here (https://www.journaldev.com/21095/java-equals-hashcode) for more info.

Anyway, this problem can cause a possible memory leak because get(...) and remove(...) methods from HashMap may not be work properly.

**Comment by MrGraycat** [comment] 2021-06-06 04:46
Line user is talking:
[https://github.com/NEZNAMY/TAB/blob/master/shared/src/main/java/me/neznamy/tab/shared/features/NameTag.java#L37](https://github.com/NEZNAMY/TAB/blob/master/shared/src/main/java/me/neznamy/tab/shared/features/NameTag.java#L37)

**Comment by A248** [comment] 2021-06-07 11:53
The default implementation of equals and hashCode is identity equality, also called reference equality.

TAB creates only a single TabPlayer per player. Reference equality is perfectly suitable here because the plugin re-uses the same instance.

When the player quits, the TabPlayer instance is removed from the map: https://github.com/NEZNAMY/TAB/blob/9fc24247368aa0ea796d322614ba9efbb93698a7/shared/src/main/java/me/neznamy/tab/shared/features/NameTag.java#L239

**Comment by NEZNAMY** [comment] 2021-06-19 08:47
Can this be closed @gamerover98 ?

**Comment by gamerover98** [comment] 2021-06-19 09:34
Nope, we've found a memory leak during world unloading. TAB keeps world instances and the world keeps all in memory.
The following screenshots are taken by YourKit from a server heapdump.

![image](https://user-images.githubusercontent.com/9408687/122637747-9e360180-d0f0-11eb-9e7b-829231bda112.png)

In this screenshot, you can see 578 worlds loaded into the memory that they were meant removed by the garbage collector.
The reason is that keeps something of the world and it doesn't be unloaded correctly.

![image](https://user-images.githubusercontent.com/9408687/122637781-ce7da000-d0f0-11eb-9b2b-b7ee45979e9a.png)

**Server version**: latest paper 1.12.2
**TAB version**: 2.8.11-pre17

**What is com.grinderwolf.swm.nms.v1_12_R1.CustomWorldServer?**
SlimeWorldManager plugin: https://www.spigotmc.org/resources/slimeworldmanager.69974/

This plugin allows you to load worlds into the memory and clone them as much as you like at the speed of light. We use it on BedWars servers and it works perfectly. (No TAB plugin in BedWars servers)

**Comment by NEZNAMY** [comment] 2021-06-19 09:37
TAB does not have any references to worlds directly. It only references the bukkit player which does. Players are removed from all maps on quit, inicluding the one you sent.

**Comment by gamerover98** [comment] 2021-06-19 09:41
> Is this rare or all the time? If rare then I might have an idea what the cause is.

All worlds have the same issue.

**Comment by NEZNAMY** [comment] 2021-06-19 09:44
Can you compile with new commits and try again?

**Comment by gamerover98** [comment] 2021-06-19 09:52
Do you mean that I've to try the latest plugin version? Yes, I'll do it as soon as I can.

Anyway, when 1.13 was released, Spigot had introduced commits like the following: https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/commits/664000a476523c44baab2d95a1044659e7f957d9

These commits prevent memory leak by adding a weak reference to those instances.

https://docstore.mik.ua/orelly/java-ent/jnut/ch13_01.htm#:~:text=ref%20Package-,The%20java.,object%2C%20known%20as%20the%20referent.

**Comment by NEZNAMY** [comment] 2021-06-19 09:53
Not release, but compile with new commits I just pushed.

**Comment by gamerover98** [comment] 2021-06-21 20:40
Same issue

**Comment by NEZNAMY** [comment] 2021-06-21 20:42
Might be another plugin requesting that value which then adds it into the map. I will change tracking to player names instead of object instance.

**Comment by gamerover98** [comment] 2021-06-22 08:35
No plugin uses your API or your plugin directly.
Same issue with the latest commits.

**Comment by NEZNAMY** [comment] 2021-06-22 09:26
Show new memory dump, it can't be same.

**Comment by gamerover98** [comment] 2021-06-24 07:49
Hello,
I've replaced your plugin with my custom Scoreboard Sidebar, BelowName and Team implementation with ProtocolLib. 
Your plugin causes the server to crash due to its memory leak. Without it, the memory is ok and the server keeps online without any issue.

I don't think that I will use your plugin in any way. I'll suggest you create a temp plugin that loads and unloads worlds. It'll help you to find the leak. 

Anyway, keep this issue opened for any update.

**Comment by NEZNAMY** [comment] 2021-06-24 07:57
I changed reference type to string instead of player, which means there is no chance the same spot is referencing the player.

**Comment by gamerover98** [comment] 2021-06-24 08:02
Ok, let me know if this new implementation fixed the issue. Let's try with what I've explained before with an old version of it and then with the newest one.

If the leak is always on it, the worlds kept in memory will be major than the loaded. I suggest you use YourKit (Free for 15 days) for monitoring it.

**Comment by NEZNAMY** [comment] 2021-06-24 08:03
You said the implementation didn't fix the issue. I need a new memory dump since it can't be the same spot.

**Comment by gamerover98** [comment] 2021-06-24 08:06
Ok sorry, I misunderstood. 
Anyway, I can't help you because I've said before, I can't provide you with a new heap dump.

**Comment by NEZNAMY** [comment] 2021-07-27 21:12
I purchased a YourKit licence to test this, however I was not able to reproduce it. All references to disconnected players are lost on garbage collection.

**Comment by Tanguygab** [comment] 2021-07-27 21:32
maybe it's an issue with SlimeWorldManager?

**Comment by NEZNAMY** [comment] 2021-11-30 18:41
I was not able to reproduce this issue. Closing for now, perhaps if the issue is still present someone else will open this again.

**Closed by NEZNAMY** 2021-11-30 18:41 UTC
Labels: Unable to reproduce
