### ISSUE TITLE
Prefixes

### ISSUE THREAD

**Issue by BigLemons123** [NEZNAMY/TAB#812] opened 2023-01-29 00:37 UTC
### Server version

1.19.3

### TAB version

3.2.4

### Describe the bug

I cannot get prefixes to work via bungeecord. I have the latest version of tab-bridge and i have everything set correctly to my knowledge but nothing shows still. Not sure why. Thanks for your time.
![2023-01-28_18 35 31](https://user-images.githubusercontent.com/110860672/215297563-bb04d26f-3d79-419b-bbcc-98305139cfa7.png)

### Expected behavior

Shows prefixes in tab

### Steps to reproduce

Installed TAB on bungeecord plugins folder and TAB-Bridge on survival and creative plugins folders.
changed groups config to the following:

_DEFAULT_:
  tabprefix: "%luckperms-prefix%"
  tagprefix: "%luckperms-prefix%"
  customtabname: "%essentials_nickname%"
  customtagname: "%essentials_nickname%" # don't forget to enable unlimited nametag mode to make this one work
  tabsuffix: "%luckperms-suffix%%afk%"
  tagsuffix: "%luckperms-suffix%%afk%"

### Additional info

I'm hoping I'm just overlooking something. Thanks again.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Tanguygab** [comment] 2023-01-29 01:06
![image](https://user-images.githubusercontent.com/45695833/215298325-621641ff-14d3-44db-aec5-c5b592150d0e.png)

Send your config.yml file
Are you using normal BungeeCord or Waterfall?

**Comment by BigLemons123** [comment] 2023-01-29 03:14
Just normal bungeecord. Here is my config. 

# https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Header-&-Footer
header-footer:
  enabled: true
  disable-in-worlds:
    - disabledworld
  disable-in-servers:
    - disabledserver
  header:
    - "<#1f72ba>&m                                                </#1f72ba>"
    - ""
    - "<#E9D5AA>&l&nBLITHE"
    - ""
    - "&7&l>> %animation:Welcome%&f %player%&7! &7&l<<"
    - "<#fbb039>Online staff: <#E9D5AA>%staffonline%"
    - "<#1f72ba>Online players: <#E9D5AA>%online%"
    - "<#1f72ba>Ping: <#E9D5AA>%ping%"
    - "%animation:time%"
    - ""
  footer:
    - ""
    - "<#fbb039>Visit our webpage %animation:web%"
    - "<#1f72ba>&m                                                </#1f72ba>"
  per-world:
    world1:
      header:
        - "an example of world with custom"
      footer:
        - "header/footer and prefix/suffix"
    world2;world3:
      header:
        - "This is a shared header for"
        - "world2 and world3"
  per-server:
    server1:
      header:
        - "an example of server with custom header"

# https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Tablist-name-formatting
tablist-name-formatting:
  enabled: true
  align-tabsuffix-on-the-right: false
  character-width-overrides: {}
  anti-override: true
  disable-in-worlds:
    - disabledworld
  disable-in-servers:
    - disabledserver

# https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Nametags
scoreboard-teams:
  enabled: true
  enable-collision: true
  invisible-nametags: false
  anti-override: true
  # https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Sorting-players-in-tablist
  sorting-types:
  - GROUPS:Admin,dev,Jr.Admin,Sr.Mod,Mod,Jr.Mod,Media,Lead-Builder,Builder,TourGuide,Vip,Tier-7,Tier-6,Tier-5,Tier-4,Tier-3,Tier-2,Tier-1,player,default
    - "PLACEHOLDER_A_TO_Z:%player%"
  case-sensitive-sorting: true
  can-see-friendly-invisibles: false
  disable-in-worlds:
    - disabledworld
  disable-in-servers:
    - disabledserver
  # https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Unlimited-nametag-mode
  unlimited-nametag-mode:
    enabled: true
    use-marker-tag-for-1-8-x-clients: false
    disable-on-boats: true
    disable-in-worlds:
      - disabledworld
    disable-in-servers:
      - disabledserver
    dynamic-lines:
      - abovename
      - nametag #the original one, combination of tagprefix + customtagname + tagsuffix
      - belowname
      - another
    static-lines:
      myCustomLine: 0.66

# https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Yellow-number
yellow-number-in-tablist:
  enabled: false
  value: "%ping%"
  disable-in-worlds:
    - disabledworld
  disable-in-servers:
    - disabledserver

# https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Belowname
belowname-objective:
  enabled: false
  number: "%health%"
  text: "&cHealth"
  disable-in-worlds:
    - disabledworld
  disable-in-servers:
    - disabledserver

# https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Spectator-fix
prevent-spectator-effect:
  enabled: false

# https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Bossbar
bossbar:
  enabled: false
  toggle-command: /bossbar
  remember-toggle-choice: false
  hidden-by-default: false
  disable-in-worlds:
    - disabledworld
  disable-in-servers:
    - disabledserver
  bars:
    ServerInfo:
      style: "PROGRESS" # for 1.9+: PROGRESS, NOTCHED_6, NOTCHED_10, NOTCHED_12, NOTCHED_20
      color: "%animation:barcolors%" # for 1.9+: BLUE, GREEN, PINK, PURPLE, RED, WHITE, YELLOW
      progress: "100" # in %
      text: "&fWebsite: &bwww.domain.com"

# https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Scoreboard
scoreboard:
  enabled: false
  toggle-command: /sb
  remember-toggle-choice: false
  hidden-by-default: false
  use-numbers: false
  static-number: 0
  delay-on-join-milliseconds: 0
  respect-other-plugins: true
  disable-in-worlds:
    - disabledworld
  disable-in-servers:
    - disabledserver
  scoreboards:
    admin:
      # Only players with tab.scoreboard.admin can see this scoreboard, others will see scoreboard1
      display-condition: "permission:tab.scoreboard.admin"
      title: "Admin scoreboard"
      lines:
        - "%animation:MyAnimation1%"
        - "&6Online:"
        - "* &eOnline&7: &f%online%"
        - "* &eCurrent World&7: &f%worldonline%"
        - "* &eStaff&7: &f%staffonline%"
        - " "
        - "&6Server Info:"
        - "* &bTPS&7: %tps%"
        - "* &bUptime&7: &f%server_uptime%"
        - "* &bMemory&7: &f%memory-used%&7/&4%memory-max%"
        - "%animation:MyAnimation1%"
    scoreboard1:
      title: "Default"
      lines:
        - "%animation:MyAnimation1%"
        - "&6My Stats:"
        - "* &eKills&7: &f%statistic_player_kills%"
        - "* &eDeaths&7: &f%statistic_deaths%"
        - "* &eHealth&7: &f%health%"
        - " "
        - "&6Personal Info:"
        - "* &bRank&7: &f%group%"
        - "* &bPing&7: &f%ping%&7ms"
        - "* &bWorld&7: &f%world%"
        - "%animation:MyAnimation1%"

# https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Ping-Spoof
ping-spoof:
  enabled: false
  value: 0

# https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Pet-name-fix
fix-pet-names:
  enabled: false

placeholders:
  date-format: "dd.MM.yyyy"
  time-format: "[HH:mm:ss / h:mm a]"
  time-offset: 0
  register-tab-expansion: false

# https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Placeholder-output-replacements
placeholder-output-replacements:
  "%essentials_vanished%":
    "yes": "&7| Vanished"
    "no": ""
  # bukkit-only placeholders used in default groups.yml, doing this as a fix
  "%afk%":
    true: " &o[AFK]&r"
    false: ""
    "%afk%": "" # if attempting to use bukkit-only placeholder on bungeecord
  "%essentials_nickname%":
    "%essentials_nickname%": "%player%" # placeholder did not parse correctly, show real name instead

# https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Conditional-placeholders
conditions:
  nick: # use it with %condition:nick%
    conditions:
      - "%player%=%essentials_nickname%"
    yes: "%player%"
    no: "~%essentials_nickname%"

placeholderapi-refresh-intervals:
  default-refresh-interval: 500
  server:
    "%server_uptime%": 1000
    "%server_tps_1_colored%": 1000
    "%server_unique_joins%": 5000
  player:
    "%player_health%": 200
    "%player_ping%": 1000
    "%vault_prefix%": 1000
  relational:
    "%rel_factionsuuid_relation_color%": 1000

# assigning groups by permission nodes instead of taking them from permission plugin
assign-groups-by-permissions: true

# if the option above is true, all groups are taken based on permissions and the one higher in this list is used as primary
# Warning! This is not sorting list and has nothing to do with sorting players in tablist!
primary-group-finding-list:
  - Owner
  - Admin
  - Mod
  - Helper
  - default

debug: false

# https://github.com/NEZNAMY/TAB/wiki/MySQL
mysql:
  enabled: false
  host: 000.0.0.0
  port: 0000
  database: tab
  username: user
  password: password

########################################################################
# BUKKIT ONLY - THE FOLLOWING SECTION IS ONLY FOR BACKEND INSTALLATION #
########################################################################

# https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Per-world-playerlist
per-world-playerlist:
  enabled: false
  # players with tab.staff will always see all players
  allow-bypass-permission: false
  # players in these worlds will always see all players
  ignore-effect-in-worlds:
    - ignoredworld
    - build
  shared-playerlist-world-groups:
    lobby:
      - lobby1
      - lobby2
    minigames:
      - paintball
      - bedwars

#####################################################################
# PROXY ONLY - THE FOLLOWING SECTION IS ONLY FOR PROXY INSTALLATION #
#####################################################################

# https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Global-playerlist
global-playerlist:
  enabled: true
  display-others-as-spectators: false
  display-vanished-players-as-spectators: true
  isolate-unlisted-servers: false
  update-latency: false
  fill-profile-key: false
  spy-servers:
    - spyserver1
    - spyserver2
  server-groups:
    lobbies:
      - survival
      - creative
    group2:
      - server1
      - server2

# Take permissions and groups from backend server instead of proxy
use-bukkit-permissions-manager: false

**Comment by NEZNAMY** [comment] 2023-01-29 09:48
`/btab debug <player>`

**Comment by BigLemons123** [comment] 2023-01-29 22:22
![2023-01-29_16 22 18](https://user-images.githubusercontent.com/110860672/215358937-185b3a29-05cf-4a53-a569-a6aa1e413903.png)
![2023-01-29_16 22 20](https://user-images.githubusercontent.com/110860672/215358943-1f24b99c-f8d9-42c4-ac33-9854afd819d2.png)

**Comment by Tanguygab** [comment] 2023-01-29 22:53
replace the - in your LuckPerms placeholders by _ (%luckperms-prefix% - > %luckperms_prefix%, same for suffix)

**Comment by BigLemons123** [comment] 2023-01-29 23:25
![2023-01-29_17 24 12](https://user-images.githubusercontent.com/110860672/215361947-4e357318-b650-48f5-a3b1-1f9dd629c94c.png)
![2023-01-29_17 24 56](https://user-images.githubusercontent.com/110860672/215361978-ce6d8e1c-d78f-4c3e-949a-67d9153bb557.png)
![2023-01-29_17 24 53](https://user-images.githubusercontent.com/110860672/215361980-bf9b55d7-2b35-4254-a5f7-1e3f79e72c77.png)


well we are getting there lol

**Comment by Tanguygab** [comment] 2023-01-30 07:27
make sure you have TAB-Bridge on all your spigot servers as well as PlaceholderAPI with the LuckPerms expansion

**Comment by NEZNAMY** [comment] 2023-01-30 10:33
Or just install LP on bungeecord?

**Comment by NEZNAMY** [comment] 2023-02-03 23:48
This is not a bug, conversation suggests it's just user asking for help. This is an issue tracker, closing this.

**Closed by NEZNAMY** 2023-02-03 23:48 UTC
Labels: Type: Bug
