### ISSUE TITLE
Velocity Tab Reload Kick

### ISSUE THREAD

**Issue by Yirf** [NEZNAMY/TAB#1205] opened 2024-01-10 05:08 UTC
### Server version

1.20.2

### TAB version

4.1.2

### Describe the bug

When reloading it kicks all players connected to the velocity proxy. Still reloads but kicks players

### Expected behavior

Should not kick the players

### Steps to reproduce

Not to sure whats the cause but we are using global playerlists

### Additional info

![image](https://github.com/NEZNAMY/TAB/assets/125339961/b0b0b307-e321-40bc-8e04-d566501a1929)

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment] 2024-01-10 09:06
Duplicate of #1187

**Closed** 2024-01-12 10:15 UTC
Labels: Type: Bug, Resolution: Out of scope
