### ISSUE TITLE
Extra tab space

### ISSUE THREAD

**Issue by Albeyzhy** [NEZNAMY/TAB#783] opened 2023-01-08 12:34 UTC
### Server version

PaperSpigot 1.8.8

### TAB version

3.2.1

### Describe the bug

If you have this:

`_DEFAULT_:
  tabprefix: "%luckperms_prefix% &7"
  tagprefix: "%luckperms_prefix% &7"
  tabsuffix: "&f&o %afk%"
  tagsuffix: " %luckperms_suffix%"`
  
The tab name is still as long as %luckperms_suffix% would be, so theres empty space...
  
This is with the ``tagsuffix: " %luckperms_suffix%"`
![image](https://user-images.githubusercontent.com/96750444/211196057-f547bfc9-471e-46c1-8c33-28de4b5374fe.png)

This is without:
![image](https://user-images.githubusercontent.com/96750444/211196121-eae3af04-8e4a-4779-bdd4-b6b4f5543fe6.png)

### Expected behavior

It shouldn't have any extra space.

### Steps to reproduce

Use this:
``_DEFAULT_:
  tabprefix: "%luckperms_prefix% &7"
  tagprefix: "%luckperms_prefix% &7"
  tabsuffix: "&f&o %afk%"
  tagsuffix: " %luckperms_suffix%"``
  in groups.yml
  And download luckperms on the server, then give yourself a suffix with  `/lp user <name> meta addsuffix 90 "ThisIsLong"`

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment] 2023-01-08 19:20
Can you send your config?

**Comment by Albeyzhy** [comment] 2023-01-09 14:11
`header-footer:
  enabled: true
  disable-in-worlds:
  - disabledworld
  header:
  - '&2★&f☆&2★ &a&l&nHEROPRISON&7 (&n%online%&7) &2★&f☆&2★'
  - ''
  footer:
  - ''
  - '&8&m━I━━━━━━━━━━━━━━━━━━━━━━━━━I━'
  - '&7/buy &8● &7/discord &8● &7/bande'
  - '&8&m━I━━━━━━━━━━━━━━━━━━━━━━━━━I━'
  per-world:
    world1:
      header:
      - an example of world with custom
      footer:
      - header/footer and prefix/suffix
    world2;world3:
      header:
      - This is a shared header for
      - world2 and world3
tablist-name-formatting:
  enabled: true
  align-tabsuffix-on-the-right: false
  character-width-overrides: {}
  anti-override: false
  disable-in-worlds:
  - disabledworld
scoreboard-teams:
  enabled: true
  enable-collision: true
  invisible-nametags: false
  anti-override: false
  sorting-types:
  - GROUPS:ejer,hadmin,admin,mod,hjælper,direktør,inspektør,officer,vagt,pvagt,hero,elite,default
  - PLACEHOLDER_A_TO_Z:%player%
  case-sensitive-sorting: true
  can-see-friendly-invisibles: false
  disable-in-worlds:
  - disabledworld
  unlimited-nametag-mode:
    enabled: false
    use-marker-tag-for-1-8-x-clients: false
    disable-on-boats: true
    disable-in-worlds:
    - disabledworld
    dynamic-lines:
    - abovename
    - nametag
    - belowname
    - another
    static-lines:
      myCustomLine: 0.66
    disable-in-servers: []
yellow-number-in-tablist:
  enabled: false
  value: '%ping%'
  disable-in-worlds:
  - disabledworld
belowname-objective:
  enabled: false
  number: '%health%'
  text: '&cHealth'
  disable-in-worlds:
  - disabledworld
prevent-spectator-effect:
  enabled: false
bossbar:
  enabled: false
  toggle-command: /bossbar
  remember-toggle-choice: false
  hidden-by-default: false
  disable-in-worlds:
  - disabledworld
  bars:
    ServerInfo:
      style: PROGRESS
      color: '%animation:barcolors%'
      progress: '100'
      text: '0'
per-world-playerlist:
  enabled: false
  allow-bypass-permission: false
  ignore-effect-in-worlds:
  - ignoredworld
  - build
  shared-playerlist-world-groups:
    lobby:
    - lobby1
    - lobby2
    minigames:
    - paintball
    - bedwars
scoreboard:
  enabled: true
  toggle-command: /sb
  remember-toggle-choice: false
  hidden-by-default: false
  use-numbers: false
  static-number: 0
  delay-on-join-milliseconds: 0
  respect-other-plugins: false
  disable-in-worlds:
  - disabledworld
  scoreboards:
    vagt:
      display-condition: "%luckperms_primary_group_name%=pvagt|%luckperms_primary_group_name%=vagt|%luckperms_primary_group_name%=officer|%luckperms_primary_group_name%=inspektør|%luckperms_primary_group_name%=direktør"
      title: '&a&l&nHEROPRISON&7 (&n%online%&7)'
      lines:
      - ''
      - '&2&lSPILLER &f&lINFO'
      - '&8 ▎ &7Rank: &f%luckperms_prefix%'
      - '&8 ▎ &7Penge: &f%vault_eco_balance_formatted%&a&l$'
      - '&8 ▎ &7Coins: &f%sb_coins%&e&l⛃'
      - ''
      - '&2&lVAGT &f&lINFO'
      - '&8 ▎ &7Kills: &f%sb_kills%'
      - '&8 ▎ &7Døde: &f%sb_døde%'
      - '&8 ▎ &7Level: &f%sb_level%'
      - ''
    fange:
      title: '&a&l&nHEROPRISON&7 (&n%online%&7)'
      lines:
      - ''
      - '&2&lSPILLER &f&lINFO'
      - '&8 ▎ &7Rank: &f%luckperms_prefix%'
      - '&8 ▎ &7Penge: &f%vault_eco_balance_formatted%&a&l$'
      - '&8 ▎ &7Coins: &f%sb_coins%&e&l⛃'
      - ''
      - '&2&lBANDE &f&lINFO'
      - '&8 ▎ &7Bande: &f%sb_bande%'
      - '&8 ▎ &7Level: &f%sb_bandelevel%'
      - '&8 ▎ &7Bank: &f%sb_bandebank%&a&l$'
      - ''

ping-spoof:
  enabled: false
  value: 0
fix-pet-names:
  enabled: false
placeholders:
  date-format: dd.MM.yyyy
  time-format: '[HH:mm:ss / h:mm a]'
  time-offset: 0
  register-tab-expansion: false
placeholder-output-replacements:
  '%essentials_vanished%':
    'yes': '&7| Vanished'
    'no': ''
  '%afk%':
    true: '&7&o&nAFK&r'
    false: ''
assign-groups-by-permissions: false
primary-group-finding-list:
- Owner
- Admin
- Mod
- Helper
- default
debug: false
mysql:
  enabled: false
  host: 127.0.0.1
  port: 3306
  database: tab
  username: user
  password: password
placeholderapi-refresh-intervals:
  default-refresh-interval: 15000
  server:
    '%tps%': 10000
  player:
    '%luckperms_suffix%': 5000
    '%luckperms_prefix%': 5000
    '%luckperms_primary_group_name%': 5000
    '%afk%': 5000`

**Comment by NEZNAMY** [comment] 2023-01-09 14:11
And this is exactly what pastebin was invented for.

**Comment by NEZNAMY** [comment] 2023-01-09 14:12
Try enabling anti-override for tablist names.

**Comment by Albeyzhy** [comment] 2023-01-09 14:12
Ok
https://pastebin.com/j0NsRzZh

**Comment by Albeyzhy** [comment] 2023-01-09 14:13
enabling anti-override for tablist names didn't help.

**Comment by NEZNAMY** [comment] 2023-01-10 15:55
Works fine for me. I also remember fixing this bug in previous versions. Are you sure you are using latest version? Check with /tab debug.

**Comment by Albeyzhy** [comment] 2023-01-10 16:13
I'm using the latest version: 
![image](https://user-images.githubusercontent.com/96750444/211603652-9c1bf4e8-4aa7-4a9e-a62f-ab9d87a230bc.png)

But it might be because i'm using 1.8.8 paperspigot.

**Comment by NEZNAMY** [comment] 2023-01-10 16:15
Try on a testing server with only TAB, LP and PlaceholderAPI.

**Comment by NEZNAMY** [comment] 2023-01-21 14:10
@Albeyzhy there's a chance another plugin is formatting player's real tablist entry, making it longer. Did you make any progress on this? I wasn't able to reproduce this issue with only TAB, LP and PlaceholderAPI.

**Comment by Albeyzhy** [comment] 2023-01-21 15:41
I've tried with only TAB, LP and PlaceholderAPI, and it still shows it longer than it should be.

Maybe you can use all my config files (groups.yml, layout.yml, config.yml) and then try.
Heres my TAB folder: https://www.mediafire.com/folder/rngkv51soubzn/TAB 👍

**Comment by NEZNAMY** [comment] 2023-01-21 16:19
![image](https://user-images.githubusercontent.com/6338394/213876246-a95eca62-843b-4c31-9279-92c27857e030.png)

**Comment by Albeyzhy** [comment] 2023-01-21 18:11
What should i send em with? just pastebin them all?

**Comment by NEZNAMY** [comment] 2023-01-21 18:29
Anything that will actually work.

**Comment by Albeyzhy** [comment] 2023-01-21 18:53
Config: https://pastebin.com/igKcGQck
Layout: https://pastebin.com/8CbHm0Hz
Groups: https://pastebin.com/7xC8FYEE

**Comment by NEZNAMY** [comment] 2023-01-21 19:44
![image](https://user-images.githubusercontent.com/6338394/213884447-6f0accab-eed2-496b-83de-63a79e90ab25.png)
Works fine.

**Comment by NEZNAMY** [comment] 2023-01-25 11:03
@Albeyzhy ?

**Comment by Albeyzhy** [comment] 2023-01-25 11:16
Yeah thats what i mean. It is like there is an invisable suffix in the tabsuffix (when i have a suffix on)

**Comment by Albeyzhy** [comment] 2023-01-25 11:17
As you can see on my first message.

**Comment by NEZNAMY** [comment] 2023-01-25 11:19
Can you test with scoreboard teams disabled? Or provide working steps to reproduce?

**Comment by Albeyzhy** [comment] 2023-01-25 11:22
Try giving yourself a prefix and a longer suffix. And i use 1.8 paperspigot, but there probably isn't any difference.

**Comment by NEZNAMY** [comment] 2023-01-25 11:22
I gave myself the suffix you wrote in your steps to reproduce.

**Comment by Albeyzhy** [comment] 2023-01-25 11:23
Maybe try a longer one

**Comment by NEZNAMY** [comment] 2023-01-25 11:27
![image](https://user-images.githubusercontent.com/6338394/214551922-c8686275-ae9f-4593-af0d-60ac9059a4de.png)
still nothing

**Comment by NEZNAMY** [comment] 2023-01-31 09:32
@Albeyzhy please try again with providing new steps to reproduce. I am not able to make any progress here as I cannot reproduce it and therefore this issue is stuck waiting for you.

**Comment by NEZNAMY** [comment] 2023-02-07 09:50
Closing bug report as invalid. If anyone else is having this issue and is willing to provide working steps to reproduce, go ahead.

**Closed** 2023-02-07 09:50 UTC
Labels: Type: Bug, Unable to reproduce
