### ISSUE TITLE
I often get a big tab through invisible placeholders

### ISSUE THREAD

**Issue by supermem99** [NEZNAMY/TAB#475] opened 2022-01-04 23:53 UTC
**Server version**
1.18.1 Paper

**Plugin version** ("latest" is not a version)
3.0.1

**Describe the bug**
Sometimes when I join my Server, the placeholder refreshes and I get a long tab...

**How to reproduce**
1. Have more placeholder in your tab like in my example:
  tabprefix: '%premiumvanish_isvanished%&8[%animation:owner_prefix%&8] {#ca191e}%reloadedutils_blinken%'
2. Join to your server
3. get this tab 
![Screenshot_1](https://user-images.githubusercontent.com/32147021/148139450-fa9ef035-5fb5-48f3-81f6-925df769c7d9.png)

**Expected behavior**
it simply should be a smaller tab.

**Actual behavior**
Have a big tab

**Additional info** (errors, screenshots, ...)

**Comment by NEZNAMY** [comment] 2022-01-31 17:23
Try with 3.0.2

**Comment by NEZNAMY** [comment] 2022-02-10 20:07
Any news @supermem99 ?

**Comment by supermem99** [comment] 2022-02-10 23:05
![Screenshot_3](https://user-images.githubusercontent.com/32147021/153511650-eadd7ff3-82bc-43ad-8e07-8e6c9fe1838a.png)

**Comment by NEZNAMY** [comment] 2022-02-11 05:06
I have no idea why and can't fix it without steps to reproduce that actually work.

**Comment by NEZNAMY** [comment] 2022-02-11 12:45
I will not be able to test them because I don't have the plugins you are using placeholders from.

**Comment by supermem99** [comment] 2022-02-11 13:23
Ok. Actually its now permanent like the picture.
But only to users from users.yml

**Comment by NEZNAMY** [comment] 2022-02-11 13:25
![image](https://user-images.githubusercontent.com/6338394/153599243-28c7e050-e16b-4443-a86a-40976ced91b7.png)
![image](https://user-images.githubusercontent.com/6338394/153599229-b01298be-075c-4a33-80c5-a1e6ee7a63b7.png)

**Comment by supermem99** [comment] 2022-02-11 13:31
Ok but its not the placeholder which have the issue

**Comment by NEZNAMY** [comment] 2022-02-11 13:32
Give me one that I can try myself without having to buy any plugins.

**Comment by supermem99** [comment] 2022-02-14 02:51
```
14.02.2022 - 03:50:44 - [TAB v3.0.2] An error occurred when refreshing placeholders
14.02.2022 - 03:50:44 - java.lang.NumberFormatException: Cannot parse null string
14.02.2022 - 03:50:44 -        at java.base/java.lang.Integer.parseInt(Integer.java:630)
14.02.2022 - 03:50:44 -        at java.base/java.lang.Integer.parseInt(Integer.java:786)
14.02.2022 - 03:50:44 -        at me.neznamy.tab.shared.features.sorting.types.Placeholder.getChars(Placeholder.java:39)
14.02.2022 - 03:50:44 -        at me.neznamy.tab.shared.features.sorting.Sorting.getTeamName(Sorting.java:109)
14.02.2022 - 03:50:44 -        at me.neznamy.tab.shared.features.nametags.NameTag.updateTeam(NameTag.java:280)
14.02.2022 - 03:50:44 -        at me.neznamy.tab.shared.features.nametags.NameTag.refresh(NameTag.java:85)
14.02.2022 - 03:50:44 -        at me.neznamy.tab.shared.features.PlaceholderManagerImpl.refresh(PlaceholderManagerImpl.java:88)
14.02.2022 - 03:50:44 -        at me.neznamy.tab.shared.features.PlaceholderManagerImpl.refresh(PlaceholderManagerImpl.java:68)
14.02.2022 - 03:50:44 -        at me.neznamy.tab.shared.CpuManager.lambda$runMeasuredTask$2(CpuManager.java:108)
14.02.2022 - 03:50:44 -        at me.neznamy.tab.shared.CpuManager.lambda$submit$5(CpuManager.java:155)
14.02.2022 - 03:50:44 -        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
14.02.2022 - 03:50:44 -        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
14.02.2022 - 03:50:44 -        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
14.02.2022 - 03:50:44 -        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
14.02.2022 - 03:50:44 -        at java.base/java.lang.Thread.run(Thread.java:833)
```

thats the cause i think

**Comment by NEZNAMY** [comment] 2022-02-14 08:05
Will be fixed in the next version. For now manually lowercase all outputs in placeholder sorting type in config.

**Comment by NEZNAMY** [comment] 2022-02-14 20:13
Original issue will likely be fixed in the next update where the feature is reworked.

**Comment by supermem99** [comment] 2022-02-15 19:55
> Will be fixed in the next version. For now manually lowercase all outputs in placeholder sorting type in config.

I did it, but its almost still there.
![Screenshot_4](https://user-images.githubusercontent.com/32147021/154138805-3e32e624-a59b-454a-8429-b1a5ce07dc4d.png)

**Closed** 2022-03-04 22:10 UTC
Labels: Bug, Unable to reproduce
