### ISSUE TITLE
Update to 1.20

### ISSUE THREAD

**Issue by Idris4ik** [NEZNAMY/TAB#920] opened 2023-06-12 11:24 UTC
### Server version

Paper 1.20

### TAB version

3.3.2

### Evidence

Update to 1.20

### Steps to reproduce (if known)

Update to 1.20

### Additional info

Update to 1.20

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included sufficient evidence of the issue
- [ ] I ticked all of the boxes without actually reading them

**Comment by Tanguygab** [comment] 2023-06-12 11:25
Duplicate of #918 and #915

**Comment by NEZNAMY** [comment] 2023-06-12 11:25
How is that a performance issue?

**Closed by Tanguygab** 2023-06-12 11:25 UTC
Labels: Type: Performance

**Comment by Idris4ik** [comment] 2023-06-12 11:47
Sorry, I mixed up it
