### ISSUE TITLE
Show boss bar on join for specific amount of time

### ISSUE THREAD

**Issue by Kore-Development** [NEZNAMY/TAB#252] opened 2020-12-15 06:11 UTC
I would like to have a boss bar only show for a specific amount of time to a player after they join. For example, send a boss bar with a website to a player for 30 seconds when they join.

**Comment by NEZNAMY** [comment] 2020-12-17 16:56
Basically a duplicate of #251 , you'd just get a plugin that runs a command on join.

**Closed** 2021-02-08 13:31 UTC
Labels: Duplicate
