### ISSUE TITLE
[Unlimited Nametags] Floating nametag plugin TAB

### ISSUE THREAD

**Issue by ShizenXD** [NEZNAMY/TAB#1198] opened 2024-01-04 09:03 UTC
### Server version

Paper 1.8.8

### TAB version

4.1.2

### Describe the bug

When I or another player moves, the tag does not move along with it, and there are times when the tag stays still and does not return to the player. In some cases, the tag multiplies. I've tested it on various forks, and it's a bug. My Discord: yukinaga. I will send some videos if needed.

### Expected behavior

# Detailed explanation of all options available at https://github.com/NEZNAMY/TAB/wiki/config.yml
header-footer:
  enabled: true
  header:
  - '%animation:LinhaTAB%'
  - ''
  footer:
  - ''
  - '%animation:online-ping-tps%'
  - ''
  - '%animation:LinhaTAB%'
  per-world:
    world1:
      header:
      - an example of world with custom
      footer:
      - header/footer and prefix/suffix
    world2;world3:
      header:
      - This is a shared header for
      - world2 and world3
  disable-condition: '%world%=disabledworld'
tablist-name-formatting:
  enabled: true
  anti-override: true
  disable-condition: '%world%=disabledworld'
scoreboard-teams:
  enabled: true
  enable-collision: false
  invisible-nametags: false
  anti-override: true
  sorting-types:
  - GROUPS:DONO,Admin,Ajudante,VIPStrix,VIPKiller,VIPElite,YT,Titanio,Esmeralda,Diamante,Ouro,Prata,Cobre,Ferro,Pedra,Terra,Membro
  - PLACEHOLDER_A_TO_Z:%player%
  case-sensitive-sorting: true
  unlimited-nametag-mode:
    enabled: true
    disable-on-boats: true
    space-between-lines: 0.22
    dynamic-lines:
    - nametag
    - abovename
    - belowname
    - another
    static-lines:
      myCustomLine: 0.66
    disable-condition: '%world%=disabledworld'
  can-see-friendly-invisibles: false
  disable-condition: '%world%=disabledworld'
belowname-objective:
  enabled: false
  number: '%health%'
  text: '&cHealth'
  disable-condition: '%world%=disabledworld'
  fancy-display-default: NPC
  fancy-display-players: '&c%health%'
prevent-spectator-effect:
  enabled: false
bossbar:
  enabled: true
  toggle-command: /bossbar
  remember-toggle-choice: false
  hidden-by-default: false
  bars:
    ServerInfo:
      style: PROGRESS
      color: '%animation:barcolors%'
      progress: '%animation:barprogress%'
      text: '%animation:bartext%'
per-world-playerlist:
  enabled: false
  allow-bypass-permission: false
  ignore-effect-in-worlds:
  - ignoredworld
  shared-playerlist-world-groups:
    lobby:
    - lobby1
    minigames:
    - paintball
scoreboard:
  enabled: true
  toggle-command: /sb
  remember-toggle-choice: false
  hidden-by-default: false
  use-numbers: false
  static-number: 0
  delay-on-join-milliseconds: 0
  respect-other-plugins: true
  scoreboards:
    scoreboard:
      title: '&c&lStrix&b&lPvP'
      lines:
      - ''
      - '&c&lNick&f&l: &f%player_displayname%'
      - '&c&lCargo&f&l: &f%vault_rank%'
      - ''
      - '&b&lClan&f&l: %simpleclans_tag_label%'
      - '&b&lKDR&f&l&f&l: &f%simpleclans_clan_total_kdr%'
      - ''
      - '&a&lMoney&f&l: &f%nexteconomy_amount%'
      - '&e&lCash&f&l: &f%jhshop_cash%'
ping-spoof:
  enabled: false
  value: 0
placeholders:
  date-format: dd.MM.yyyy
  time-format: '[HH:mm:ss / h:mm a]'
  time-offset: 0
placeholder-output-replacements:
  '%essentials_vanished%':
    'yes': '&7| Vanished'
    'no': ''
  '%afk%':
    true: ' &o[AFK]&r'
    false: ''
  '%essentials_nickname%':
    '%essentials_nickname%': '%player%'
conditions:
  nick:
    conditions:
    - '%player%=%essentials_nickname%'
    true: '%player%'
    false: ~%essentials_nickname%
placeholderapi-refresh-intervals:
  default-refresh-interval: 300
  '%server_uptime%': 1000
  '%server_tps_1_colored%': 1000
  '%server_unique_joins%': 5000
  '%player_health%': 1000
  '%player_ping%': 1000
  '%vault_prefix%': 400
  '%rel_factionsuuid_relation_color%': 1000
assign-groups-by-permissions: false
primary-group-finding-list:
- DONO
- Admin
- Ajudante
- VIPStrix
- VIPKiller
- VIPElite
- YT
- Titanio
- Esmeralda
- Diamante
- Ouro
- Prata
- Cobre
- Ferrp
- Pedra
- Terra
- Default
debug: false
mysql:
  enabled: false
  host: 127.0.0.1
  port: 3306
  database: tab
  username: user
  password: password
use-online-uuid-in-tablist: true
global-playerlist:
  enabled: false
layout:
  enabled: false
  direction: COLUMNS
  default-skin: mineskin:1753261242
  enable-remaining-players-text: true
  remaining-players-text: '... and %s more'
  layouts:
    staff:
      condition: permission:tab.staff
      fixed-slots:
      - '1|&3RAM&f:'
      - 2|&b%memory-used%MB / %memory-max%MB
      - 3|&8&m
      - '4|&3TPS&f:'
      - 5|&b%tps%
      groups:
        staff:
          condition: permission:tab.staff
          slots:
          - 24-40
        players:
          slots:
          - 44-80
    default:
      fixed-slots: null
      groups:
        staff:
          condition: permission:tab.staff
          slots:
          - 24-40
        players:
          slots:
          - 44-80
  empty-slot-ping-value: 1000
playerlist-objective:
  enabled: true
  value: '%ping%'
  disable-condition: '%world%=disabledworld'
  fancy-value: '&7Ping: %ping%'

### Steps to reproduce

Basicamente apenas pular ou se deslocar com fly ou correndo

### Additional info

![Captura de Tela (220)](https://github.com/NEZNAMY/TAB/assets/107296268/9f338d28-9d25-4afb-8c51-11005fbe2482)

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [x] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment] 2024-01-04 10:43
![image](https://github.com/NEZNAMY/TAB/assets/6338394/d4e779b6-2b49-485b-8eaf-ec6d9c302d3c)
Did google translate fail here?

![image](https://github.com/NEZNAMY/TAB/assets/6338394/3d244f65-e81b-43aa-a1e8-90ba4bda9d2e)

Try without any other plugins.

**Comment by ShizenXD** [comment] 2024-01-04 10:56
já testei sem nenhum outro PL não adianta

**Comment by ShizenXD** [comment] 2024-01-04 10:57
já testei sem nenhum outro PL não adianta

**Comment by ShizenXD** [comment] 2024-01-04 10:58
I've already tested it without any other PL, it's no use

**Comment by NEZNAMY** [comment] 2024-01-04 10:59
Make a video of the issue and also show list of plugins on that video to be sure.

**Comment by ShizenXD** [comment] 2024-01-04 10:59
yukinaga. discord, Prints Videos

**Comment by ShizenXD** [comment] 2024-01-04 11:00
![image](https://github.com/NEZNAMY/TAB/assets/107296268/d2600249-f7a2-4e36-9eda-87a0a5841659)
List Plugins

**Comment by NEZNAMY** [comment] 2024-01-04 11:01
You said you tried with no other plugins, but now it looks like you never removed any?

**Comment by ShizenXD** [comment] 2024-01-04 11:03
I just put

**Comment by ShizenXD** [comment] 2024-01-04 11:04
but both with and without there is no point

**Comment by NEZNAMY** [comment] 2024-01-04 11:04
Remove all plugins except TAB and if it still happens, zip the entire server folder (without the world I guess) and upload it somewhere. I will test it on a copy of your server.

**Comment by ShizenXD** [comment] 2024-01-04 11:05
I can't upload the video on GithHub, add me to discord

**Comment by NEZNAMY** [comment] 2024-01-04 11:05
You can upload a video to youtube and send a link. Discord contact is only available for customers.

**Comment by ShizenXD** [comment] 2024-01-04 11:08
![image](https://github.com/NEZNAMY/TAB/assets/107296268/199b87e4-220e-4cee-97cf-b1d910dfd591)

**Comment by NEZNAMY** [comment] 2024-01-04 11:09
If you still get the issue with this setup, zip the entire server folder (without the world) and upload it somewhere. I will try it.

**Comment by ShizenXD** [comment] 2024-01-04 11:09
![image](https://github.com/NEZNAMY/TAB/assets/107296268/1638c136-a8df-448c-b528-0eeb57977a82)

**Comment by NEZNAMY** [comment] 2024-01-04 11:12
Random screenshots won't help, since you cannot capture motion on a screenshot. Do what I asked you to do.

**Comment by ShizenXD** [comment] 2024-01-04 11:14
Server em ZIP

**Comment by NEZNAMY** [comment] 2024-01-04 11:30
[Unable to reproduce](https://www.youtube.com/watch?v=h7JMaSA0qfM). We can notice some known issues, such as:
* When looking at own nametag using F5, the movement [will be delayed](https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Unlimited-nametag-mode#additional-note-2---f5-view), which is mostly caused by movement animation, which is only present on other entities, not player themselves
* When sneaking, [armor stands appear in wrong position for a frame](https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Unlimited-nametag-mode#additional-note-7---client-sided-visual-bugs), which is a client-sided bug that got fixed years ago.

Other than these two well known unfixable issues, I was not able to reproduce the issue you described.

**Comment by ShizenXD** [comment] 2024-01-04 11:32
tem de usar 2 clients

**Comment by NEZNAMY** [comment] 2024-01-04 11:33
I have no idea why do you not speak english, I do not understand that language and never gave any hint suggesting otherwise.

**Comment by ShizenXD** [comment] 2024-01-04 11:34
I have to use 2 clients, what happens is that when I crouch the tag floats and when I run it doesn't move with me, I noticed that this only happens with Inlimited Funcion, but if I disable this function I can't make long tags, please fix it

**Comment by ShizenXD** [comment] 2024-01-04 11:34
I have to use 2 clients, what happens is that when I crouch the tag floats and when I run it doesn't move with me, I noticed that this only happens with Inlimited Funcion, but if I disable this function I can't make long tags, please fix it

**Comment by ShizenXD** [comment] 2024-01-04 11:35
I have to use 2 clients, what happens is that when I crouch the tag floats and when I run it doesn't move with me, I noticed that this only happens with Inlimited Funcion, but if I disable this function I can't make long tags, please fix it

**Comment by NEZNAMY** [comment] 2024-01-04 11:35
Have you even seen the video I sent? It works completely fine for me using a copy of your server you sent.

**Comment by ShizenXD** [comment] 2024-01-04 11:36
I don't think you saw it but the tag isn't moving with you, it's loose, it tries to fly so you can see

**Comment by NEZNAMY** [comment] 2024-01-04 11:37
It is moving, just delayed, which I described in the first note in my message.

**Comment by ShizenXD** [comment] 2024-01-04 11:38
I understand the F5 bug, but this happens to everyone on the server, not just me

**Comment by ShizenXD** [comment] 2024-01-04 11:39
Everyone on the server suffers from this problem

**Comment by ShizenXD** [comment] 2024-01-04 11:39
when you are moving you have this problem

**Comment by NEZNAMY** [comment] 2024-01-04 11:39
Suffers from what? Seeing delayed movement when using preview?

**Comment by ShizenXD** [comment] 2024-01-04 11:40
I see the players with the tags floating, the same thing happens to them, they come to me in the same way

**Comment by NEZNAMY** [comment] 2024-01-04 11:41
Make a video.

**Comment by ShizenXD** [comment] 2024-01-04 11:42
ok

**Comment by ShizenXD** [comment] 2024-01-04 11:43
Client Vanilla

**Comment by ShizenXD** [comment] 2024-01-04 11:50
https://www.mediafire.com/file/s8tw9lvy4qke0r2/unknown_2024.01.04-08.47.mp4/file

**Comment by ShizenXD** [comment] 2024-01-04 11:53
In events like Gladiator, it's chaos, all the players' tags keep moving

**Comment by NEZNAMY** [comment] 2024-01-04 12:01
I checked the video and didn't notice anything new besides a tiny delay when jumping, which is unfixable, because the plugin already teleports armor stands to player's new position as soon as possible.

**Comment by ShizenXD** [comment] 2024-01-04 21:20
But this delay only occurs on my server

**Comment by ShizenXD** [comment] 2024-01-04 21:21
and it's chaos all the players are complaining about this delay

**Comment by ShizenXD** [comment] 2024-01-04 21:21
another thing when you crouch the tag buga

**Comment by ShizenXD** [comment] 2024-01-04 21:22
Sometimes when you move too fast the tag disappears and doesn't come back, you have to close Minecraft and open it again

**Comment by NEZNAMY** [comment] 2024-01-04 21:22
> and it's chaos all the players are complaining about this delay

I already told you this is not fixable. Disable unlimited nametags.



> Sometimes when you move too fast the tag disappears and doesn't come back, you have to close Minecraft and open it again

Make a video.

**Comment by ShizenXD** [comment] 2024-01-04 21:29
It's not that simple to disappear it's rarely but it happens

**Comment by ShizenXD** [comment] 2024-01-04 21:29
![image](https://github.com/NEZNAMY/TAB/assets/107296268/efe54da7-5a3b-425b-82ee-043d70a5c240)
Disable Unlimited Nametags

**Comment by ShizenXD** [comment] 2024-01-04 21:30
![image](https://github.com/NEZNAMY/TAB/assets/107296268/f2c2c79f-8d25-468c-a4fb-8d394df5ef1a)
Enable Unlimited Nametags

**Comment by NEZNAMY** [comment] 2024-01-04 21:30
That's because mojang added a 16 character limit, which was removed in 1.13. All you need to do is to update your game. Did you know 1.20.4 is out?

**Comment by ShizenXD** [comment] 2024-01-04 21:31
Is this Limit in the Fork or in the Client?

**Comment by NEZNAMY** [comment] 2024-01-04 21:32
Then the brazilian community will have short prefixes. You cannot have everything. No other plugin had this feature and this is why.
The limit is client sided. You would need to hack everyone in brazil and force-install a modified copy of the game without the limit, which is something I don't recommend doing.

**Comment by ShizenXD** [comment] 2024-01-04 21:35
But it's strange that there are servers where the tag is normal in 1.8.8

**Comment by NEZNAMY** [comment] 2024-01-04 21:36
They are probably within the 16 character limit or use some kind of workaround like TAB does.

**Comment by ShizenXD** [comment] 2024-01-04 21:36
scoreboard-teams:
  enable-collision: false 
What is this function for?

**Comment by ShizenXD** [comment] 2024-01-04 21:36
Does this limit of 16 also include the name?

**Comment by NEZNAMY** [comment] 2024-01-04 21:37
It's collision, obviously. A feature added to the game years ago back in 1.9. Please stop asking random questions, this is not support.
[The 16 character limit](https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Nametags#limitations) is for each prefix, name and suffix separately. Just like the wiki says.

**Comment by ShizenXD** [comment] 2024-01-04 21:46
I talked to a very strong developer from Brazil and he told me that the issue of the limit of 16 really doesn't have much to do, but the bug disappears and even the delayed displacement problem is a problem with the plugin

**Comment by NEZNAMY** [comment] 2024-01-04 21:49
That's right, if you disable unlimited nametags, you will no longer run into these potential problems. I see nothing wrong with that logic.

**Comment by ShizenXD** [comment] 2024-01-04 21:51
But if I disable it, spaces and colors won't work correctly.

**Comment by ShizenXD** [comment] 2024-01-04 21:51
![Uploading Captura de Tela (225).png…]()

**Comment by NEZNAMY** [comment] 2024-01-04 21:52
That's right, MC has a 16 character limit in those ancient versions. Nothing I can do about that.

**Comment by ShizenXD** [comment] 2024-01-04 23:55
04.01.2024 - 07:21:43 - [TAB v4.1.2] An error was thrown when executing task
04.01.2024 - 07:21:43 - java.lang.NullPointerException: null
04.01.2024 - 07:21:43 - 	at me.neznamy.tab.shared.backend.features.unlimitedtags.BackendNameTagX.lambda$sneak$1(BackendNameTagX.java:191)
04.01.2024 - 07:21:43 - 	at me.neznamy.tab.shared.cpu.CpuManager.lambda$runMeasuredTask$5(CpuManager.java:147)
04.01.2024 - 07:21:43 - 	at me.neznamy.tab.shared.cpu.CpuManager.run(CpuManager.java:173)
04.01.2024 - 07:21:43 - 	at me.neznamy.tab.shared.cpu.CpuManager.lambda$submit$3(CpuManager.java:98)
04.01.2024 - 07:21:43 - 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
04.01.2024 - 07:21:43 - 	at java.util.concurrent.FutureTask.run(Unknown Source)
04.01.2024 - 07:21:43 - 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
04.01.2024 - 07:21:43 - 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
04.01.2024 - 07:21:43 - 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
04.01.2024 - 07:21:43 - 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
04.01.2024 - 07:21:43 - 	at java.lang.Thread.run(Unknown Source)

**Comment by NEZNAMY** [comment] 2024-01-16 19:52
I have fixed this error, although the plugin may not work properly if the situation happens again. 
What other issues are you experiencing? I think we already went through everything at this point.

**Comment by PouleyX** [comment] 2024-01-26 17:58
Hello, I have a similar problem : https://youtu.be/zcIIoRxhKqs

**Comment by NEZNAMY** [comment] 2024-01-26 17:59
> Hello, I have a similar problem : https://youtu.be/zcIIoRxhKqs

This one was fixed in dev builds.

**Comment by PouleyX** [comment] 2024-01-26 19:35
neither

**Comment by NEZNAMY** [comment] 2024-01-26 19:37
Then what is the issue you are describing?

**Comment by PouleyX** [comment] 2024-01-26 19:41
what I mean is that the nametag is not transparent, even with the vanillia client

**Comment by NEZNAMY** [comment] 2024-01-26 19:42
I asked if you are talking about that issue and you said no. What is your server and client version?

**Comment by PouleyX** [comment] 2024-01-26 19:44
my bad, client 1.20.4 - paper 1.20.4

**Comment by NEZNAMY** [comment] 2024-01-26 19:51
[Unable to reproduce](https://www.youtube.com/watch?v=69_rmnTiBWg).

**Comment by ShizenXD** [comment] 2024-02-28 02:02
ola tudo bem ? migrei para a 1.20.4 vou dar uma testada eu estava na 1.8

**Comment by NEZNAMY** [comment] 2024-02-28 07:32
I don't speak that language.

**Comment by shooutz** [comment] 2024-06-03 18:02
lmao
why is this still open?

**Comment by NEZNAMY** [comment] 2024-06-03 18:32
Because bug was not confirmed to be fixed and unlimited nametag feature will be marked for removal next week.

**Comment by shooutz** [comment] 2024-06-03 18:40
> Because bug was not confirmed to be fixed and unlimited nametag feature will be marked for removal next week.

will "unlimited nametag" be removed? Do you mean the additional lines?
I would suggest that he use precisely this resource, the Brazilian community (I'm BR) considers using the prefix like this "§a§lVIP/§9§lOWNER" etc. however there is a limit of 32 total characters in the nametag

**Comment by NEZNAMY** [comment] 2024-06-03 18:41
Yes, the entire feature will be removed. An announcement will be made in a week when 1.21 releases.

**Comment by NEZNAMY** [comment] 2024-06-13 18:28
Unlimited nametag mode was marked for removal and no more bugs will be fixed. See https://gist.github.com/NEZNAMY/f4cabf2fd9251a836b5eb877720dee5c for more info.

**Closed by NEZNAMY** 2024-06-13 18:28 UTC
Labels: Type: Bug
