### ISSUE TITLE
NameTAG bug

### ISSUE THREAD

**Issue by PanHaskins** [NEZNAMY/TAB#518] opened 2022-03-07 21:08 UTC
### Server version

Purpur 1.18.2

### TAB version

3.1.0

### Describe the bug

![image](https://user-images.githubusercontent.com/58113388/157109237-b1e17ce1-25dc-4431-901d-b8c048fb33ba.png)

### Expected behavior

![image](https://user-images.githubusercontent.com/58113388/157109614-20f8fa02-9cc1-407c-b515-5d79ee276ff3.png)

Without the nickname of the player bugging in the second line.

### Steps to reproduce

1. Add below name in groups.yml
2. Setup this in config.yml:

  unlimited-nametag-mode:
    enabled: true
    use-marker-tag-for-1-8-x-clients: false
    disable-on-boats: true
    space-between-lines: false
    disable-in-worlds:
    - disabledworld
    dynamic-lines:
    - abovename
    - nametag
    - belowname
    - another
    static-lines:
      myCustomLine: 0.66
    disable-in-servers: []

3. in MC use command /tab reload

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment] 2022-03-07 21:11
Works for me. You probably have an incompatible plugin, but I have no idea which one since you decided to not send your plugin list.

**Comment by PanHaskins** [comment] 2022-03-10 21:02
I used CMI plugin

`10.03.2022 - 21:45:20 - [TAB v3.1.0] Something just tried to add player Reaper into team EReaper (expected team: 04ReaperA)
10.03.2022 - 21:45:20 - [TAB v3.1.0] Something just tried to add player GamerDaniel29 into team EGamerDaniel29 (expected team: 19GamerDaniel29A)
10.03.2022 - 21:45:20 - [TAB v3.1.0] Something just tried to add player 11pavlkk into team E11pavlkk (expected team: 1911pavlkkA)
10.03.2022 - 21:45:20 - [TAB v3.1.0] Something just tried to add player PanHaskins into team EPanHaskins (expected team: 03PanHaskinsA)
10.03.2022 - 21:45:40 - [TAB v3.1.0] Something just tried to add player ALPHA into team EALPHA (expected team: 19ALPHAA)
10.03.2022 - 21:45:40 - [TAB v3.1.0] Something just tried to add player HEXOR_Fps into team EHEXOR_Fps (expected team: 01HEXOR_FpsA)
10.03.2022 - 21:45:40 - [TAB v3.1.0] Something just tried to add player Reaper into team EReaper (expected team: 04ReaperA)
10.03.2022 - 21:45:40 - [TAB v3.1.0] Something just tried to add player GamerDaniel29 into team EGamerDaniel29 (expected team: 19GamerDaniel29A)
10.03.2022 - 21:45:40 - [TAB v3.1.0] Something just tried to add player 11pavlkk into team E11pavlkk (expected team: 1911pavlkkA)
10.03.2022 - 21:45:40 - [TAB v3.1.0] Something just tried to add player AlikoveCZE into team EAlikoveCZE (expected team: 19AlikoveCZEA)
10.03.2022 - 21:45:40 - [TAB v3.1.0] Something just tried to add player PanHaskins into team EPanHaskins (expected team: 03PanHaskinsA)
`

**Comment by NEZNAMY** [comment] 2022-03-10 21:02
CMI is not the cause. There is something else.

**Comment by MrGraycat** [comment] 2022-03-11 05:53
Are you using eGlow if so what version? you may need to update to it's latest version.

**Comment by NEZNAMY** [comment] 2022-03-11 20:32
Let us know if it was the cause and if yes, close this issue.

**Closed** 2022-03-11 20:35 UTC
Labels: Bug, Unable to reproduce
