### ISSUE TITLE
Broken on 1.19 Waterfall while using ViaVersion on Survival/Creative servers

### ISSUE THREAD

**Issue by TomLewis** [NEZNAMY/TAB#617] opened 2022-06-14 12:31 UTC
### Server version

1.19 Waterfall to 1.18.2 ViaVersion

### TAB version

3.1.1

### Describe the bug

I cant allow 1.19 clients to connect to my 1.18.2 proxy because Tab breaks and prevents clients entering.

We have Tab 3.1.1 working on Waterfall in 1.18.2 with 1.18.2, but when I upgraded to Waterfall 1.19 while keeping my 1.18.2+ViaVersion any client 1.18 or 1.19 that connects gets errors related to Tab plugin, which is installed on the waterfall.

![This is an image](https://cdn.discordapp.com/attachments/555462232209621003/985497868062302279/Screenshot_2022-06-12_11.56.14.png)

This is the error from the bungee running tab, the survival is using tab bridge.

https://gist.github.com/TomLewis/949005ad5907da8e5056a1904ec98e37

### Expected behavior

Not error and allow clients to connect.

### Steps to reproduce

1. Use latest waterfall and install tab
2. Install tab bridge onto survival server
3. Have 1.18.2 PurPur survival server and install the latest ViaVersion dev version
4. Without Tab players can use 1.19 clients to connect to the 1.18.2 server, with tab it breaks this.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment] 2022-06-14 12:32
How is this not a duplicate of #611 ? Also where did you read that the plugin supports 1.19?

**Comment by TomLewis** [comment] 2022-06-14 12:35
I do not get the message `Your server version is completely unsupported` anywhere from that other ticket.
This is extra information for how to re-produce so it can be tested.

Is this being worked on? I dont want to have to remove tab just to allow 1.19 clients to connect.

**Comment by NEZNAMY** [comment] 2022-06-14 12:35
https://github.com/NEZNAMY/TAB/issues/611#issuecomment-1152364252

**Comment by TomLewis** [comment] 2022-06-14 12:49
Best I submit information if its useful, my case differs in the fact im unsing a bungee setup.

**Comment by NEZNAMY** [comment] 2022-06-14 12:49
Bungeecord had a breaking change that requires a plugin update.

**Comment by SueFox** [comment] 2022-06-14 13:18
Hey! I also have the same problem, when I upgrade waterfall to 1.19-496, the player will get the error in the screenshot above as soon as the player enters. Even if I delete all other plugins and leave only Tab (I'm using the release version 3.1.1, and I'm using translation software, there may be inaccuracies)

**Comment by SueFox** [comment] 2022-06-14 13:20
At the same time, an error will also appear on my client, which may help you to fix this bug (but it will not cause the game to be closed directly)
https://pastes.dev/cNpwDiyDy9

**Comment by NEZNAMY** [comment] 2022-06-14 14:13
For the n-th time: Latest public TAB release (3.1.1) does **not** support 1.19.

**Comment by SueFox** [comment] 2022-06-14 14:15
> 第 n 次：最新的公共 TAB 版本 (3.1.1) 不**支持**1.19。

The same is true for paper1.12.2 I use

**Comment by NEZNAMY** [comment] 2022-06-14 14:24
Exactly! https://github.com/NEZNAMY/TAB/wiki/Compatibility#supported-server-versions

**Comment by TomLewis** [comment] 2022-06-16 12:33
Shall I just remove tab for now if this is gogin to take a long time? I need 1.19 clients to be able to connect.

**Comment by NEZNAMY** [comment] 2022-06-16 12:50
Those are issues that will be solved in the next update.

**Closed** 2022-06-18 05:55 UTC
Labels: Duplicate, Feature request

**Comment by TomLewis** [comment] 2022-06-19 19:02
Thank you! good job! I got this live 20 mins ago and we now have 1.19 clients connecting!
