### ISSUE TITLE
Error with worldguard

### ISSUE THREAD

**Issue by WarnDa** [NEZNAMY/TAB#851] opened 2023-03-24 19:55 UTC
### Server version

Pufferfish+ 1.19.3

### TAB version

this build : https://github.com/NEZNAMY/TAB/actions/runs/4502317977

### Stack trace

https://pastebin.com/BdK4WHhj

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment] 2023-03-24 20:03
Duplicate of #843 , cause by extra flags plugin.

**Closed by NEZNAMY** 2023-03-24 20:03 UTC
Labels: Type: Error
