### ISSUE TITLE
[PremiumVanish] Error with old versions of PV

### ISSUE THREAD

**Issue by sannielollie** [NEZNAMY/TAB#1171] opened 2023-12-10 23:59 UTC
### Server version

Spigot 1.19.2

### TAB version

4.1.2

### Describe the bug

![image](https://github.com/NEZNAMY/TAB/assets/8124429/bbbd8afa-2cda-4fe3-92aa-81a37a20b8f0)
Placeholder is not working. Parses just fine
![image (1)](https://github.com/NEZNAMY/TAB/assets/8124429/3361cacf-6c91-4eff-84e8-6cb29ae33a10)
![btab parse](https://github.com/NEZNAMY/TAB/assets/8124429/94161c3c-b15e-46b2-9592-e190eb31c1d8)
Before i used the same placholder on BungeeTabListPlus wich worked flawless. Switched plugins because this one looked easier and the other had issues with the latest MC update.
Im also using the latest (5.0.1) bridge plugin on the PaperSpigot server.
In the errors.log i only see this: https://paste.gg/p/anonymous/c37c4dbe59b6419b9cf79687fe8dcb94 wich i dont think is related to this, but maybe to PremiumVanish.
This is the debug output
![tab](https://github.com/NEZNAMY/TAB/assets/8124429/0fc5c716-1683-4ede-b954-688b84253de7

### Expected behavior

It should show the rank before the name, instead of the placeholder before the name.

### Steps to reproduce

Honestly i dont know. I just downloaded the plugin, installed it on Waterfall and the bridge plugin on PaperSpigot, Nothing special really. 
Then i tried using the placeholder %vault_prefix% but it just doesnt seem to "read" it through the bridge plugin from the PaperSpigot backend server.

### Additional info

I checked the compatibility page, and already changed disable_tab_list_rewrite: true to false.

### Checklist

- [ ] I ticked all of the boxes without actually reading them
- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment] 2023-12-11 06:04
The issue is most likely caused by that error which broke the plugin. Are you using a decently recent version of PV?

**Comment by sannielollie** [comment] 2023-12-11 07:44
Yes thank you, that was the cause. I missed a update. Sorry for making a support ticket for this, i could not find a support Discord server and usually people dont reply on the comment section at Spigot. 
Thanks again for solving the issue, appreciate it!

**Comment by NEZNAMY** [comment] 2023-12-11 07:49
The error will be fixed to prevent it from happening to others in the future. This was not a support ticket, this was an error report, which is fine. Support is currently [not provided](https://github.com/NEZNAMY/TAB?tab=readme-ov-file#provided-services) due to high demand.

**Comment by sannielollie** [comment] 2023-12-11 16:19
Unfortunately i cannot browse old backups at my hosting provider, but i remember it was around 2 years old. 
Back-end runs at home and i always update everything there, i just forgot about waterfall because it just "runs fine".
Another mistake learned :)

**Closed** 2024-04-23 17:25 UTC
Labels: Resolution: Added / Fixed, Type: Compatibility issue
