### ISSUE TITLE
Could not pass event NickChangeEvent to TAB v3.1.4

### ISSUE THREAD

**Issue by SrMonsterYT** [NEZNAMY/TAB#701] opened 2022-09-02 21:59 UTC
### Server version

Pufferfish git-Pufferfish-34 (MC: 1.19.2)

### TAB version

TAB v3.1.4

### Describe the bug

https://mclo.gs/ifzTSl1

### Expected behavior

no error

### Steps to reproduce

I don't know how this happened

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Tanguygab** [comment] 2022-09-02 22:05
I'm not sure but I think this is an issue with Essentials, try to update it, if it's not fixed, then I believe NEZ added a null check in newer dev-builds to prevent the error https://github.com/NEZNAMY/TAB/actions

**Comment by NEZNAMY** [comment] 2022-09-02 22:46
How is this not a duplicate of #684 ? Even title is the same.

**Closed** 2022-09-20 14:01 UTC
Labels: Bug, Duplicate
