### ISSUE TITLE
unlimited-nametag-mode does not support Chinese

### ISSUE THREAD

**Issue by CCjun6** [NEZNAMY/TAB#958] opened 2023-07-02 13:29 UTC
### Server version

BC 1.20.1

### TAB version

4.0.2

### Describe the bug

Does not support Chinese and has no effect after filling in
It was supported in the previous version and I hope that the later version will continue to support it

### Expected behavior

Support Chinese

### Steps to reproduce

Fill in the sub-service in Chinese

### Additional info

![M`S$KFTE7XZPR{H4~3_2JUV](https://github.com/NEZNAMY/TAB/assets/128166019/2de81f32-2af5-42fd-b25e-ffdf02fbff87)

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Tanguygab** [comment] 2023-07-02 13:30
https://github.com/NEZNAMY/TAB/wiki/How-to-save-the-config-in-UTF8-encoding

**Comment by NEZNAMY** [comment] 2023-07-02 13:36
![image](https://github.com/NEZNAMY/TAB/assets/6338394/b1fac1a5-67ae-4a8b-8b07-abbd17335b4a)
Nothing has changed regarding UTF-8 config reading in ages.

**Comment by CCjun6** [comment] 2023-07-02 14:29
> https://github.com/NEZNAMY/TAB/wiki/How-to-save-the-config-in-UTF8-encoding

It doesn’t work. I tried it. No matter how I switch to Chinese, it won’t change.
How about you turn around for me? these three words
登录服

**Comment by NEZNAMY** [comment] 2023-07-02 14:32
I deleted my config, so I got the freshly generated one. I didn't even need to change encoding, because plugin does that by default. I just pasted the symbols and got the result
![image](https://github.com/NEZNAMY/TAB/assets/6338394/29eb5072-49b1-4160-aa60-aa05f8e6ac7a)

**Comment by CCjun6** [comment] 2023-07-02 14:37
I just converted it to utf-8 and then pasted it in, but it doesn’t work
![image](https://github.com/NEZNAMY/TAB/assets/128166019/88517bf8-032c-4a86-a11d-e3a5937b9d41)


> 我删除了我的配置，所以我得到了新生成的配置。我什至不需要更改编码，因为插件默认会这样做。我刚刚粘贴了符号并得到了结果 ![图像](https://user-images.githubusercontent.com/6338394/250363544-29eb5072-49b1-4160-aa60-aa05f8e6ac7a.png)

**Comment by NEZNAMY** [comment] 2023-07-02 14:39
Looks like it works in nametags though. Either way, this is an issue with your file encoding. The plugin does properly support those symbols, I just tested it, even with a clean config.

**Comment by CCjun6** [comment] 2023-07-02 14:41
> Looks like it works in nametags though. Either way, this is an issue with your file encoding. The plugin does properly support those symbols, I just tested it, even with a clean config.

![image](https://github.com/NEZNAMY/TAB/assets/128166019/641b4f87-2e58-4cb7-b47b-c44fb17bad52)

**Comment by CCjun6** [comment] 2023-07-02 14:42
![@UEGZ$6(~~VDP9N}@A4@LJE](https://github.com/NEZNAMY/TAB/assets/128166019/c2c8bd30-f5d6-4a4c-8672-7f8355491f0e)
This is the configuration of the previous versions. I used Chinese at the time and there was no problem.
Now I'm using the latest version and regenerated the configuration file and configured it, but it just doesn't work

**Comment by NEZNAMY** [comment] 2023-07-02 14:42
Check `/btab parse <player> %server%` to see actual output of the placeholder. But that's out of scope of issues.

**Comment by CCjun6** [comment] 2023-07-02 14:45
> Check `/btab parse <player> %server%` to see actual output of the placeholder. But that's out of scope of issues.

![image](https://github.com/NEZNAMY/TAB/assets/128166019/f2be3dc1-30cb-4678-b688-5aeb045dde83)

**Comment by NEZNAMY** [comment] 2023-07-02 14:48
If you run `/btab debug <player>`, does it say the values are disabled for that player? And what exactly is the issue? Armor stands still appearing in that server?

**Comment by CCjun6** [comment] 2023-07-02 14:50
> If you run `/btab debug <player>`, does it say the values are disabled for that player? And what exactly is the issue? Armor stands still appearing in that server?

i didn't understand you
My problem now is
I want to disable unlimited-nametag-mode on a subserver
But no matter what I try, it doesn't work

**Comment by NEZNAMY** [comment] 2023-07-02 14:51
Run the command for a player who should be disabled and show output.

**Comment by CCjun6** [comment] 2023-07-02 14:57
![image](https://github.com/NEZNAMY/TAB/assets/128166019/c484ebb6-36cd-4aa0-872c-ae375bf7ae1b)
你是要看这个吗？

**Comment by JingHai-Lingyun** [comment] 2023-07-02 15:09
Excuse me,are you sure this plugin has full Chinese config support?

**Comment by CCjun6** [comment] 2023-07-02 15:11
![image](https://github.com/NEZNAMY/TAB/assets/128166019/4b36e56c-bf66-4ab1-a108-ee3fb78f2d34)
Why not continue to use this format
He supports Chinese

**Comment by NEZNAMY** [comment] 2023-07-02 15:11
The plugin has full UTF-8 support. I was able to reproduce this bug after finally given something to work with even when using normal server names.

**Comment by JingHai-Lingyun** [comment] 2023-07-02 15:15
if you can reproduce this bug and know why it happend, plz fix it soon
it is important for Chinese servers.

**Comment by NEZNAMY** [comment] 2023-07-02 15:16
This has nothing to do with chinese symbols. I was able to reproduce the bug using normal server names. Repeating the same thing over and over slows me down in actually fixing it.

**Comment by NEZNAMY** [comment] 2023-07-02 15:17
Stop trolling me or I will not fix this bug.

**Comment by CCjun6** [comment] 2023-07-02 15:21
> Stop trolling me or I will not fix this bug.
i didn't harass you i don't know why you think that
If disabled successfully he will look like this
The pictures in the comments above will not appear
![DQ~`VYWMI@D4E@O4C_(O{SF](https://github.com/NEZNAMY/TAB/assets/128166019/e68d49f2-e66e-4bb6-aca2-966d280cd27c)

**Comment by NEZNAMY** [comment] 2023-07-02 15:22
Yes I know there is a bug. I am working on fixing it. No need to tell me there's a bug 10 times after I confirmed it.

**Comment by CCjun6** [comment] 2023-07-02 15:25
ok, sorry to bother you

**Comment by NEZNAMY** [comment] 2023-07-02 15:35
Download latest build of [TAB](https://github.com/NEZNAMY/TAB/suites/14009461056/artifacts/781879730) and [Bridge](https://github.com/NEZNAMY/TAB-Bridge/suites/14009451276/artifacts/781877729) and try again.

**Comment by CCjun6** [comment] 2023-07-02 15:50
> 下载最新版本的[TAB](https://github.com/NEZNAMY/TAB/suites/14009461056/artifacts/781879730)和[Bridge](https://github.com/NEZNAMY/TAB-Bridge/suites/14009451276/artifacts/781877729)，然后重试。

![3KX{SI}OEGV@Q7T11)B0@F5](https://github.com/NEZNAMY/TAB/assets/128166019/a89e44ff-6262-4b74-a487-16244d87c9f7)
好像起作用了
但是名字全部消失了

**Comment by Tanguygab** [comment] 2023-07-02 15:51
send your config.yml

**Comment by CCjun6** [comment] 2023-07-02 15:58
![Uploading H(%1OVYX@{GWV~BFB5DIT3X.png…]()
Sorry, I just regenerated the configuration and filled in
And he did it! ! !
thank you very much good author

**Closed** 2023-07-02 15:59 UTC
Labels: Type: Bug, Unable to reproduce
