### ISSUE TITLE
enabled MySQL break whole groups.yml file

### ISSUE THREAD

**Issue by xNikees911** [NEZNAMY/TAB#517] opened 2022-03-06 23:29 UTC
### Server version

Spigot 1.17.1 (paper latest)

### TAB version

3.1.0

### Describe the bug

Hi, I have enabled MySQL support, setup whole groups.yml file and after enabled mysql all not working from this file per rank. Only header and footer from config.yml work fine. But when I disable one more time mysql support all gonna work fine. I have weight in in LuckPerms, also I have primary-group-finding-list feature with same weights like in LuckPerms. I my opinion MySQL breaks whole groups.yml and there is problem. Also when I have enabled mysql I have blank tables in tab_groups database.

### Expected behavior

None

### Steps to reproduce

I wrote above

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Tanguygab** [comment] 2022-03-07 07:04
well the whole point of the MySQL feature is to store properties in a remote database instead of local files.... so of course groups.yml is completely ignroed, as specified on the wiki

**Comment by NEZNAMY** [comment] 2022-03-07 19:20
Run /tab mysql upload and /tab reload and all of your problems will be magically solved.

**Comment by xNikees911** [comment] 2022-03-07 19:25
Still same, also got only 6 ranks from 16 like in groups.yml file 
![image](https://user-images.githubusercontent.com/89745544/157103833-74f19b9c-82c2-4b7a-8a5f-6c8cc70b9e37.png)
TAB view still not work
![image](https://user-images.githubusercontent.com/89745544/157103875-7b33ce00-bedc-4e57-8ae5-d012c34a405d.png)

**Comment by NEZNAMY** [comment] 2022-03-07 19:28
So upload command didn't upload everything? It looks like you didn't even read the mysql wiki page in the first place, despite saying you did. Support is only provided to buyers on discord. What you said so far is not a bug, but the way mysql function works.

**Comment by xNikees911** [comment] 2022-03-07 19:29
Bro, I got also error in your errors file 
![image](https://user-images.githubusercontent.com/89745544/157104343-097b1dbb-84fc-42de-9fba-bbc3ad9cc650.png)

**Comment by NEZNAMY** [comment] 2022-03-07 19:34
Error shows upload command failed due to an error. Will be fixed in the next version.

**Comment by xNikees911** [comment] 2022-03-07 19:41
Why I don't see any prefix, colors on tab from setup ranks? like for Wlasciciel rank from screenshot above.

**Comment by xNikees911** [comment] 2022-03-08 19:45
> Why I don't see any prefix, colors on tab from setup ranks? like for Wlasciciel rank from screenshot above. ![image](https://user-images.githubusercontent.com/89745544/157106032-b83917d4-7d19-4a73-9adb-f1e3306619f7.png)

any help for that? or it's bug

**Comment by NEZNAMY** [comment] 2022-03-08 19:46
Conversion bug will be fixed in the next version. Casual help is not provided here.

**Comment by NEZNAMY** [comment] 2022-03-09 09:14
Turns out group names are case-sensitive when loading from MySQL. I will solve that too.

**Comment by xNikees911** [comment] 2022-03-09 18:22
> Turns out group names are case-sensitive when loading from MySQL. I will solve that too.

And you see :) It was better to write that this is not a mistake and you will not help me, and it was enough to check ...

**Comment by NEZNAMY** [comment] 2022-03-09 19:18
I already said it's a bug which will be fixed in the next version.

**Closed** 2022-04-01 08:36 UTC
Labels: Bug, Error
