### ISSUE TITLE
Permission based suffix/prefix

### ISSUE THREAD

**Issue by theextraordinarypassionatedesignmonkeys** [NEZNAMY/TAB#42] opened 2019-09-24 15:24 UTC
**What would i want?**
The ability to give groups a permission so that the permission can be used to define who gets the specified prefix/suffix. 
**Why could this be usefull?**
For larger networks it is hard to manage the suffixes and prefixes of all the different ranks available. And with permission support you can copy paste the config file in each server and use the permissions to disable a group that should only be on 1 server and not on the whole netwerk.
Also with MySQL support there could be a table like tag_groups for example with a structure like this: http://prntscr.com/padgsg (But then with the correct properties for all the different options.)
With those 2 features you can make it a whole lot easier to manage the prefixes and suffixes on a server.
**How could it be added?**
It could be added just by adding a line for use-mysql: true/false in the advancedconfig and by having a mysql credentials spot in the same config file.

**Comment by NEZNAMY** [comment] 2019-09-24 15:30
You seem to be talking about two completely different requests.
First one being mysql support which is duplicate of #17 , second one being very unclear. It looks like making players assign into groups by permission instead of taking group from permission plugin ? Like NTE does ? Or just something like a placeholder with permission-based result ?

**Comment by tomkeuper** [comment] 2019-09-24 15:56
Yes players assigned into groups by permission because you can set a permission to false for other servers. And indeed like NTE does.
And i was trying to make clear that the MySQL support would also benefit from this.

**Comment by NEZNAMY** [comment] 2019-09-24 16:00
Permission node will not be needed, can generally be "tab.group.<groupname>". I was thinking about doing this before but i got stuck. When checking for that permission, how does the plugin get list of all groups (permissions) to check for ? Should it be from Groups section ? Or sorting list ? Also, what if someone (accidentally?) has more than one permission ?

**Comment by tomkeuper** [comment] 2019-09-24 16:10
For checking permissions it should indeed check what groups are assigned and after that check what the value is of the permission. And if the user has more permission then one it should get the highest group in the list OR the groups could have an priority property and then it should give the prefix/suffix of the group with the highest number, this number will also sort the users in the tab menu. And i think that the priority properties is best because this could also be easily added to mysql once there is support for that.

**Closed** 2020-03-12 17:28 UTC
Labels: Feature request
