### ISSUE TITLE
NPCs in tablist

### ISSUE THREAD

**Issue by wlm1455925277** [NEZNAMY/TAB#810] opened 2023-01-26 06:14 UTC
### Server version

1.19.3

### TAB version

3.2.4

### Stack trace

I use the 3.2.4 version on the bungee server, and the tab on the spigot server will always stay in this state. Note that it stays all the time! My server version is 1.19.3!

![2023-01-26_14 13 23](https://user-images.githubusercontent.com/87473483/214769800-9c4d4304-4ce3-48a7-a3df-893e74ce5b71.png)

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by MrGraycat** [comment] 2023-01-26 06:20
[https://github.com/NEZNAMY/TAB/wiki/Known-issues#1---1192---npcs-in-tablist](https://github.com/NEZNAMY/TAB/wiki/Known-issues#1---1192---npcs-in-tablist)

if you don't believe it uninstall TAB and find out. It's not caused by TAB.
Duplicate of #778 and prob some others

**Closed by MrGraycat** 2023-01-26 06:20 UTC
Labels: Type: Error

**Comment by wlm1455925277** [comment] 2023-01-26 06:29
> https://github.com/NEZNAMY/TAB/wiki/Known-issues#1---1192---npcs-in-tablist
> 
> 如果您不相信它，请卸载 TAB 并找出答案。它不是由 TAB 引起的。 #778 的副本并探测其他一些

However, I have always existed, and I didn't disappear all of a sudden!

**Comment by wlm1455925277** [comment] 2023-01-26 06:30
> > https://github.com/NEZNAMY/TAB/wiki/Known-issues#1---1192---npcs-in-tablist
> > 如果您不相信它，请卸载 TAB 并找出答案。它不是由 TAB 引起的。#778 的副本并探测其他一些
> 
> 但是，我一直存在，我并没有突然消失！

The description in the wiki is that it will suddenly appear and then disappear. For me, he will not disappear, he will always exist!

**Comment by MrGraycat** [comment] 2023-01-26 06:30
Well let me say it like this TAB doesn't handle npc's. Remove TAB and find out
