### ISSUE TITLE
A error of the option perworldplayerlist

### ISSUE THREAD

**Issue by MightCly** [NEZNAMY/TAB#1006] opened 2023-07-29 13:14 UTC
### Server version

1.8.8

### TAB version

4.0.3

### Describe the bug

The option "PerWorld-playerlist" does not work
i can (have all permissions) and all players default rank can view all players connecteds.

### Expected behavior

I know

### Steps to reproduce

per-world-playerlist:
  enabled: true
  allow-bypass-permission: false
  ignore-effect-in-worlds:
  shared-playerlist-world-groups:
    lobby:
    - none

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment] 2023-07-29 13:15
Try without any plugins that could interfere. Also send your full config.

**Comment by NEZNAMY** [comment] 2023-08-04 11:12
[Unable to reproduce](https://www.youtube.com/watch?v=ImnO3KIME2U). This issue, especially on server versions older than their player base, is usually caused by another plugin trying to do a similar thing, such as minigame plugins. Reproduce without any unrelated plugins.

**Comment by NEZNAMY** [comment] 2023-08-10 08:35
Assuming user has died and closing this as caused by another plugin.

**Closed by NEZNAMY** 2023-08-10 08:35 UTC
Labels: Type: Bug, Unable to reproduce
