### ISSUE TITLE
[TAB]: [config.yml] Missing configuration section "header-footer.header" of type List, using default value []

### ISSUE THREAD

**Issue by SrMonsterYT** [NEZNAMY/TAB#1379] opened 2024-10-30 00:21 UTC
### Server version

1.21.3

### TAB version

TAB v5.0.1

### Plugin list

Velocity 3.4.0-SNAPSHOT (git-08a42b37-b449)

### Describe the bug

when updating the server from 1.20.4 to 1.21.3 these errors appeared in the console:

image: https://prnt.sc/2_TVcVy_tYGW

plugins: https://prnt.sc/ibTdk75yzpxv

VelocityScoreboardAPI-1.0.4

server : Velocity 3.4.0-SNAPSHOT (git-08a42b37-b449)

my config: https://mclo.gs/ycaEHt1

```[21:14:25 INFO] [VelocityScoreboardAPI]: Successfully injected Scoreboard API.
[21:14:26 WARN] [TAB]: [config.yml] Missing configuration section "header-footer.header" of type List, using default value [].
[21:14:26 WARN] [TAB]: [config.yml] Missing configuration section "header-footer.footer" of type List, using default value [].
[21:14:26 WARN] [TAB]: [config.yml] Missing configuration section "header-footer.disable-condition" of type String, using default value %world%=disabledworld.
[21:14:26 WARN] [TAB]: [config.yml] Configuration section "header-footer.per-server.survivalsf;survivalsf2" has unknown key "disable-condition". Valid keys: [header, footer]
[21:14:26 WARN] [TAB]: [config.yml] Configuration section "header-footer.per-server.skyblock2" has unknown key "disable-condition". Valid keys: [header, footer]
[21:14:26 WARN] [TAB]: Found a total of 5 issues.
[21:14:26 INFO] [TAB]: Enabled in 118ms```

### Expected behavior

no error

### Steps to reproduce

update for 1.20.3 velocity

### Additional info

_No response_

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment] 2024-10-30 05:53
How is this a bug? It is clearly a programmed mesaage to appear when something is wrong with the config.

**Comment by SrMonsterYT** [comment] 2024-10-30 12:29
> How is this a bug? It is clearly a programmed message to appear when something is wrong with the config.

but I can't find the error, that's the problem, I've tried everything, the new configuration requires me to set the per-server option 2-3 times?

```header-footer:
  enabled: true
  per-server:
    server1:
      header:
        - ""
      footer:
        - ""
  per-server:      
    server2:
      header:
        - ""
      footer:
        - ""```
I've tried everything but nothing works

**Comment by NEZNAMY** [comment] 2024-10-30 12:32
It expects you to have a default header and footer. See default config for an example. You can also ignore the warns if you are not interested in resolving them, but it's not a bug. Please don't ask for help in github issues.

**Comment by SrMonsterYT** [comment] 2024-10-30 12:34
for me it's a bug because i've never had problems like this, and is there any way i can get your support on discord? even if i pay i don't care, the only way that worked was like this, it looks like you changed how the plugin worked?

```header-footer:
  enabled: true
  per-server:
    survivalsf;survivalsf2:
    disable-condition: '%world%=disabledworld'
  header:
    - "&r"
  footer:
    - "&r"
  disable-condition: "%world%=disabledworld"
  per-server:
    Lobby:
  header:
    - "&r"
  footer:
    - "&r"
  disable-condition: "%world%=disabledworld"
  per-server:
    server3:
      header:
        - "an example of server with custom header"```

**Comment by NEZNAMY** [comment] 2024-10-30 12:41
I have added more config checks, including this one, in 5.0.0, to which you updated recently and called it "updating to 1.20.3". When you click on "new issue" you have a link to a discord server where a person who has nothing better to do is willing to provide support to free users. You can also find the link in README on the main github page.

**Closed** 2024-10-30 14:09 UTC
Labels: Support is not provided in github issues
