### ISSUE TITLE
[BungeeCord] Proxy installation causing increased traffic usage

### ISSUE THREAD

**Issue by SrMonsterYT** [NEZNAMY/TAB#1232] opened 2024-02-13 22:07 UTC
### Server version

waterfall-1.20-562

### TAB version

TAB-4.1.3-SNAPSHOT.jar

### Describe the bug

since I put the TAB plugin on my bungeecord, I noticed a huge increase in bandwidth usage on my server, I asked my ddos protection why my bandwidth increased by 2TB, they told me that there is some plugin sending too many boss bars to the server and this causes the increase in bandwidth and the only plugin that can cause this is TAB, it's the only one that was on my bungeecord, how can I solve this?

this has never happened before, it only started after I updated TAB to bungeecord to synchronize it

### Expected behavior

not using so much bandwidth

### Steps to reproduce

use the TAB plugin in bungeecord

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment] 2024-02-13 22:12
Did you disable tab expansion in config? Having it enabled on proxy causes plugin message spam to make the expansion return value immediately on request. Are you using bossbar feature in TAB? Do you have any animations? How could they know what exactly is consuming it?

**Comment by SrMonsterYT** [comment] 2024-02-13 22:14
> Did you disable tab expansion in config? Having it enabled on proxy causes plugin message spam to make the expansion return value immediately on request. Are you using bossbar feature in TAB? Do you have any animations? How could they know what exactly is consuming it?

what is the option in the settings?

**Comment by NEZNAMY** [comment] 2024-02-13 22:15
It's literally called bossbar. You can disable it and see if it's better or not.

**Comment by SrMonsterYT** [comment] 2024-02-13 22:15
config: https://mclo.gs/J1A7DLh

I had an increase of 2 TB of bandwidth in my ddos protection

**Comment by SrMonsterYT** [comment] 2024-02-13 22:16
> It's literally called bossbar. You can disable it and see if it's better or not.

I don't use the bossbar option

**Comment by SrMonsterYT** [comment] 2024-02-13 22:19
> Your config has both bossbar and expansion disabled. How could TAB be possibly sending too many boss bars? I cannot do anything without any evidence.

https://prnt.sc/uL1GQipYMzAy

it's the only plugin on my server that does this, and the only plugin that's in bungeecord using tags, I reported it to ddos protection and they told me that the problem is in the TAB and scoreboard plugin

**Comment by NEZNAMY** [comment] 2024-02-13 22:20
What is "tx, 208 rx" and how does it relate to TAB? Why don't you temporarily remove TAB to see if it's acutally the cause?

**Comment by SrMonsterYT** [comment] 2024-02-13 22:21
> What is "tx, 208 rx" and how does it relate to TAB? Why don't you temporarily remove TAB to see if it's acutally the cause?

how do I remove the tab from all the servers and leave the server without a tab? 

how will i know if it will reduce i would have to leave the server for 2 weeks to know if it really is the tab

**Comment by NEZNAMY** [comment] 2024-02-13 22:23
Try looking into tools that will get you a live view (or at least a recent history). There is absolutely no evidence suggesting there is a bug in TAB that needs fixing.

**Comment by SrMonsterYT** [comment] 2024-02-13 22:24
> Try looking into tools that will get you a live view (or at least a recent history). There is absolutely no evidence suggesting there is a bug in TAB that needs fixing.

in the last 2 weeks it was the only plugin i added to bungeecord, and my ddos protection pointed to the Tab and scoreboard plugin, can you tell me if there is a plugin that monitors this? it was the only change i made in the last 2 weeks since the problem started

**Comment by NEZNAMY** [comment] 2024-02-13 22:25
I am not aware of any plugin that monitors this. Show the evidence pointing at TAB.

**Comment by SrMonsterYT** [comment] 2024-02-13 22:29
> I am not aware of any plugin that monitors this. Show the evidence pointing at TAB.

that's when I updated to the version you sent me

https://github.com/NEZNAMY/TAB/issues/1211#issuecomment-1910354203

**Comment by NEZNAMY** [comment] 2024-02-13 22:32
Remove animations and check back in 2 weeks. Until you give evidence I cannot do anything.

**Comment by SrMonsterYT** [comment] 2024-02-13 22:34
> Remove animations and check back in 2 weeks or whatever. Until you give evidence I cannot do anything.

is there any way I can activate the debug and see or some jar you can send me to see or analyze if it really is the TAB, because I'm almost 100% sure it is

**Comment by NEZNAMY** [comment] 2024-02-13 22:37
There is no effective solution I can implement into the plugin. Until you provide evidence, I cannot do anything.

**Comment by SrMonsterYT** [comment] 2024-02-13 23:08
> There is no effective solution I can implement into the plugin. Until you provide evidence, I cannot do anything.

removing the animations and getting results see: https://prnt.sc/kNJE4krvaRyN

tab with animation https://prnt.sc/0Z-1f_GPlwn6

**Comment by NEZNAMY** [comment] 2024-02-13 23:20
I have no idea what tx and rx means. Did that solve your problem?

**Comment by SrMonsterYT** [comment] 2024-02-13 23:22
> I have no idea what tx and rx means. Did that solve your problem?

https://copperegg.com/what-do-tx-and-rx-refer-to-in-the-network-charts/#:~:text=TX%20and%20RX%20are%20abbreviations,2019%7CKnowledge%20Base%7CComments%20Off

https://minecraft.fandom.com/wiki/Debug_screen -> https://prnt.sc/cZPnV8y6qrKY

**Comment by NEZNAMY** [comment] 2024-02-13 23:25
Does that mean it solved your problem?

**Comment by SrMonsterYT** [comment] 2024-02-13 23:28
> Does that mean it solved your problem?

Yes, it reduced the bandwidth that players send to the server, is there a way to solve this?

**Comment by NEZNAMY** [comment] 2024-02-13 23:29
Solve what? You want animations without animations? That's not how it works.

**Comment by SrMonsterYT** [comment] 2024-02-13 23:31
> Solve what? You want animations without animations? That's not how it works. You either have them or not.

this never happened when the plugin was on spigot, it only happened when I put it on bungeecord, no other plugin causes this only TAB

Are you telling me that the only solution is to remove the animations instead of sending me a jar with a solution?

**Comment by NEZNAMY** [comment] 2024-02-13 23:33
What kind of solution are you expecting? Do you understand that animations work by spamming packets?

**Comment by SrMonsterYT** [comment] 2024-02-13 23:59
> What kind of solution are you expecting? Do you understand that animations work by spamming packets?

this never happened when the plugin was in spigot, one solution would be for you to add support for mixed configuration, as you are seeing this causing problems for people using animations in bungeecord

**Comment by NEZNAMY** [comment] 2024-02-14 00:02
What is support for mixed configuration supposed to do and how do I do it?

**Comment by SrMonsterYT** [comment] 2024-02-14 00:05
> What is support for mixed configuration supposed to do and how do I do it?

not needing to use the tab plugin on bungeecord and doing like many plugins, being able to synchronize the tab via mysql between 2 servers, this problem only started when I added this plugin to bungeecord, and you know that this is a problem or if the person uses it Bungeecord is useless, the animations can never be used

**Comment by SrMonsterYT** [comment] 2024-02-14 00:29
> What is support for mixed configuration supposed to do and how do I do it?

removing some animations I discovered the official problem, the problem is the animations, but the main cause is the animations in the groups

animations: https://mclo.gs/wRi8AzJ
groups: https://mclo.gs/CJYf3Um

**Comment by NEZNAMY** [comment] 2024-02-14 07:01
How am I supposed to make animations work without sending packets?

**Comment by SrMonsterYT** [comment] 2024-02-14 16:12
> How am I supposed to make animations work without sending packets?

allowing you to synchronize TAB on 2 servers instead of using bungeecord, because the problem only happens when it's on bungeecord, and if you see above, you don't need to remove the animations the problem only happens when the animations are in the groups folder, see the folder above after I removed the animations from the groups prefix solved the problem.

**Comment by SrMonsterYT** [comment] 2024-02-14 16:15
> Animations send the same amount of packets regardless of where the plugin is installed. Give it a try using your F3 method. [Feature requests are closed](https://github.com/NEZNAMY/TAB?tab=readme-ov-file#provided-services).

when I removed the group animations it solved the problem
when I removed the group animations it solved the problem, this could be a problem in the groups part

**Comment by NEZNAMY** [comment] 2024-02-14 16:16
Create a simple example that you believe sends more packets than it should and I'll test it.

**Comment by SrMonsterYT** [comment] 2024-02-14 16:16
> Create a simple example that you believe sends more packets than it should and I'll test it.

https://github.com/NEZNAMY/TAB/issues/1232#issuecomment-1942902489

**Comment by SrMonsterYT** [comment] 2024-02-14 16:17
I just sent you my configuration of groups.yml and animations.yml, I removed these animations and it solved the problem.

**Comment by SrMonsterYT** [comment] 2024-02-14 16:21
these are all the animations I have: https://mclo.gs/9HwbL6w
these are the animations I removed: https://mclo.gs/wRi8AzJ
these are the groups where the animations and groups were https://mclo.gs/CJYf3Um

and the problem was solved by just removing the prefix animations

look how the animations used to be in the players' prefix, now I've removed it and put in no animation: https://prnt.sc/djc3OLpsPyrk

**Comment by NEZNAMY** [comment] 2024-02-14 16:23
Your entire configuration is not a "simple example". What I meant is 1 animation for 1 group that when used causes this. Another reason why this went up is because proxy has more players assuming you have at least 2 servers connected, so naturally you receive packets for updating more players than when just on the backend.

**Comment by SrMonsterYT** [comment] 2024-02-14 16:27
> Your entire configuration is not a "simple example". What I meant is 1 animation for 1 group that when used causes this. Another reason why this went up is because proxy has more players assuming you have at least 2 servers connected, so naturally you receive packets for updating more players than when just on the backend.

I've been using your plugin for more than 4 years, and this never happened, it only happened when I put it on bungeecord, that's the problem, you say you don't have time to create a mixed configuration or for suggestions, but this is not a suggestion it's a problem solution not only for me but for thousands of people who use this plugin and go to add it to bungeecord and don't even know how much bandwidth it consumes, this never happened only after I put it in bungeecord, you could allow synchronization by mysql between 2 servers only, put it as a premium version of your plugin so you would not spend your time without making a profit, allow synchronization between 2 servers and make it only for those who have the premium version of the plugin, I would buy it without any problem.

**Comment by NEZNAMY** [comment] 2024-02-14 16:30
Creating a complicated solution for global playerlist on backend would have the same result, since working with more players = animating more players = sending more packets.
I had premium version out there for 3 years and you never even considered buying it, but now that I removed it you suddenly out of nowhere do? 
This "issue" is a natural side effect of your setup and nothing can be done about it. Nobody is forcing you to use ultra fast RGB animations.

**Comment by SrMonsterYT** [comment] 2024-02-14 16:35
> Creating a complicated solution for global playerlist on backend would have the same result, since working with more players = animating more players = sending more packets. I had premium version out there for 3 years and you never even considered buying it, but now that I removed it you suddenly out of nowhere do? This "issue" is a natural side effect of your setup and nothing can be done about it. Nobody is forcing you to use ultra fast RGB animations.

for me this plugin has always been free I've never seen the premium version, and also if there was something like synchronizing 2 servers in the premium version I would only buy it now, because I'm now synchronizing 2 servers, sorry if I didn't know there was a premium version

**Comment by NEZNAMY** [comment] 2024-02-14 16:36
I already said everything. I explained where the increased packet count comes from, which is exactly the reason why you have it on proxy and implementing it on backend would not solve this issue, in fact, it would "add" this there as well. I also said feature requests are closed.
Anything unanswered left before I close this?

**Comment by SrMonsterYT** [comment] 2024-02-14 16:39
> I already said everything. I explained where the increased packet count comes from, which is exactly the reason why you have it on proxy and implementing it on backend would not solve this issue, in fact, it would "add" this there as well. I also said feature requests are closed. Anything unanswered left before I close this?

this plugin is in the lobby, survival and skyblock and this has never happened, it only happened when I put it in bungeecord, so yes if I took it out of the proxy it would solve the problem and I would have the animations, but it's no use you don't accept that there is a problem, and this doesn't happen with all animations only with the ones in the groups, I feel sorry for people who don't know when to add this plugin to bungeecord without a warning that the bandwidth will increase

**Comment by NEZNAMY** [comment] 2024-02-14 16:42
Holy shit I'll explain it to you like to a baby this time:
Imagine you have 3 servers, 10 players on each server. You have plugin on backend. You are receiving 10 animation packets (1 for each player), since you can only see players on your own server. Suddenly you install the plugin on proxy and enable global playerlist. This time, you can see 30 players because you want global playerlist. All 30 players animate, which means you suddenly receive 30 packets instead of the original 10. Do you finally understand?

**Comment by SrMonsterYT** [comment] 2024-02-14 16:45
> Holy shit I'll explain it to you like to a baby this time: Imagine you have 3 servers, 10 players on each server. You have plugin on backend. You are receiving 10 animation packets (1 for each player), since you can only see players on your own server. Suddenly you install the plugin on proxy and enable global playerlist. This time, you can see 30 players because you want global playerlist. All 30 players animate, which means you suddenly receive 30 packets instead of the original 10. Do you finally understand?

yes now I understand there was no need to be rude, I didn't mean to offend you in any way, but you know that synchronizing 2 servers instead of putting it on bungeecord would solve the whole problem, because I wouldn't be using the tab in skyblock and lobby, nor in minigames in the future, I mean that if I have 1,000 players on all servers, and I just wanted to synchronize 2 servers and not the whole network, that would be a solution, but okay, again sorry I didn't mean to offend you or stress you out

**Comment by NEZNAMY** [comment] 2024-02-14 16:48
I can look into getting those 2 features to work better together to avoid sending packets for players a player cannot see, but like you said, it will only help owners with 1000 players who only want to sync a few servers at most, not if you want to see all players.

**Comment by SrMonsterYT** [comment] 2024-02-14 16:53
> I can look into getting those 2 features to work better together to avoid sending packets for players a player cannot see, but like you said, it will only help owners with 1000 players who only want to sync a few servers at most, not if you want to see all players.

Thank you for your understanding and this would help a lot, especially because a server with 1,000 players on the bungeecord would be chaos, and synchronizing just 2 servers would be incredible so I don't need to tab on skyblock, lobby and minigames, making the tab less players on the proxy, I would love it and many other servers should be grateful if you did something, thanks.

**Comment by NEZNAMY** [comment] 2024-02-14 17:09
I did it, but that doesn't mean you'll get to the same level as you would without global playerlist.

**Comment by SrMonsterYT** [comment] 2024-02-14 17:15
> I did it, but that doesn't mean you'll get to the same level as you would without global playerlist.

How do I download it and do I just need to change the jar? Or do I need to configure something?

**Comment by NEZNAMY** [comment] 2024-02-14 17:16
https://github.com/NEZNAMY/TAB/actions/runs/7904804742
![image](https://github.com/NEZNAMY/TAB/assets/6338394/58d49f4d-0cd2-465a-90ff-09ab9ae213ea)
I thought I made the text obvious enough. You just replace the jar. That's how [updating](https://github.com/NEZNAMY/TAB/wiki/Installation#updating-the-plugin) works.

**Comment by SrMonsterYT** [comment] 2024-02-14 22:16
sorry for the delay i was doing several tests to be 100% sure and let you know, the problem was solved in 60%, but there is still the problem, the only solution would be to have how to synchronize 2 servers only without having to use the bungeecord, the problem is in the bungeecord, when the tab is in the bungeecord it increases the bandwidth a lot, my monthly TB consumption in ddos protection is 5-6 TB, now it is 7-8 TB, it has increased a lot, if I had a way to synchronize 2 servers I would solve 100% of the problem, putting the tab in the bungeecord is not a good option for most people, I have a total of 100 players, even with this update I only need to have 300 players and I will have the same problem as in the past, so unfortunately the only solution would be to have a way to synchronize 2 servers by mysql that would be incredible

that's as far as it goes: https://prnt.sc/h9J5i82QCprY

without animation in the group it goes to 70 RX

**Comment by NEZNAMY** [comment] 2024-02-14 22:20
... and we're back to square one. No.

**Comment by SrMonsterYT** [comment] 2024-02-14 22:25
For me, having a server with 100-120 players was a 60% improvement, but if the server grew to 300 players I'd have the same problem as in the past, but unfortunately for me it's better without animation in the groups.

the good news is that from yesterday to today there was no increase in bandwidth, I was at 87%, and now it's down to 86%.

see i'm glad it really was the problem and it's been solved: https://prnt.sc/PoiKP3KmjNDw

**Comment by NEZNAMY** [comment] 2024-02-14 22:27
You are running a server with 300 players and had to pick the worst and cheapest host in your country? This is going in loops and I'm not interested. I told you everything several times already.

**Comment by SrMonsterYT** [comment] 2024-02-14 22:29
> You are running a server with 300 players and had to pick the worst and cheapest host in your country? This conversation is going in loops and I'm not interested. I told you everything several times already.

you got it wrong, i said i have 100 - 120 players a day, i don't have 300, i said that if one day i have 300 players i would have the problem of the past.

and my server is an i9 10°, 128GB, 2TB SSD, dedicated

and the problem isn't with the server my tps is 20.20.20 the problem is with the use of bandwidth in ddos protection

**Comment by NEZNAMY** [comment] 2024-02-14 22:31
I will not give in to your delusion of the problem. Until you finally come up with something valid like the one thing you said earlier today, there is nothing I can do and will consider this solved. The rest is in your hands - disabling RGB animations.

**Comment by SrMonsterYT** [comment] 2024-02-14 22:34
> I will not give in to your delusion of the problem. Until you finally come up with something valid like the one thing you said earlier today, there is nothing I can do and will consider this solved. The rest is in your hands - disabling RGB animations.

the problem is not in the RGB, it's in the groups part, and also because the TAB is in the bungeecord, I don't understand why you're angry I did the test for you I turned off the server with 100 people to test for you, I recommend you mention in your guide that using animations in groups.yml will cause bandwidth increase.

note, I'm using RGB colors and it was fine, I just disabled the animations, it's the animations that cause the problem, not the RGB colors.

**Comment by NEZNAMY** [comment] 2024-02-14 22:42
Using animations increasing bandwidth is such basic logic I didn't even think of mentioning it.
You are refusing to cooperate and luckily I have no obligation to deal with this.
Also I never asked you to turn off your server. I made an improvement and called it a day. I don't even care if you use it or not. Fixed an issue, marked as solved and moved on. Simple.
Unless you provide any evidence of redundant packet sends, I will consider this solved.

**Comment by SrMonsterYT** [comment] 2024-02-14 22:43
> Using animations increasing bandwidth is such basic logic I didn't even think of mentioning it. You are refusing to cooperate and luckily I have no obligation to deal with this. Also I never asked you to turn off your server. I made an improvement and called it a day. I don't even care if you use it or not. Fixed an issue, marked as solved and moved on. Simple. Unless you provide any evidence of redundant packet sends, I will consider this solved.

I don't understand why you're rude with your words, but thanks for everything I'll use it without animations in the groups, and sorry for anything, and thanks for the help

**Comment by NEZNAMY** [comment] 2024-02-14 22:46
You are making me angry by refusing to understand what I am saying and repeating the same over and over despite clearly being told feature requests are closed and it wouldn't even solve this issue.

**Comment by SrMonsterYT** [comment] 2024-02-14 23:38
i'm brazilian sorry the translator didn't translate correctly, sorry again

**Closed** 2024-04-23 17:25 UTC
Labels: Resolution: Added / Fixed, Type: Performance
