### ISSUE TITLE
[Velocity] Minimessage hex-colors displaying as legacy colors

### ISSUE THREAD

**Issue by Lion-King287** [NEZNAMY/TAB#1256] opened 2024-03-30 00:21 UTC
### Server version

Velocity 3.3.0 / Paper 1.20.4

### TAB version

4.1.2 (+ brige on subservers)

### Describe the bug

If you use minimessage hex-codes in the tablist or in the nametag (tablist) it will be converted to normal minecraft-colors.
![image](https://github.com/NEZNAMY/TAB/assets/74682634/417c986f-fea9-42ef-93d4-1113b9066046)
![image](https://github.com/NEZNAMY/TAB/assets/74682634/0f85b0a5-f9b3-4ccd-ac19-44c59bf2f162)

### Expected behavior

It should display the hex-codes normally.

### Steps to reproduce

1. Use mini-message hex-codes in the tablist
2. Check the tablist ingame

### Additional info

```yml
header-footer:
  enabled: true
  header:
  - <rainbow><st>                                                </st></rainbow>
  - '<aqua><bold>LOCOBROKO.NET NETZWERK</bold>'
  - '<gray>Es sind <white>%online% <gray>Spieler online.'
  - ''
  footer:
  - ''
  - '<gray>Hostey by <aqua>tube-hosting.com'
  - <rainbow><st>                                                </st></rainbow>
```

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by Tanguygab** [comment] 2024-03-30 08:36
/btab debug <player>
send the output

**Comment by NEZNAMY** [comment] 2024-03-30 09:15
How is this not a duplicate of #1210 ?

**Comment by Lion-King287** [comment] 2024-03-30 13:41
> `/btab debug <player>` send the output

![image](https://github.com/NEZNAMY/TAB/assets/74682634/54cfa55f-932b-4b51-b4e0-5ae51f32b52b)
![image](https://github.com/NEZNAMY/TAB/assets/74682634/e4ff1c0c-f384-4fe7-9614-74488a10874e)



> How is this not a duplicate of #1210 ?

I mean you wrote in the issue that the bug was fixed in the last build at that time - I am now using the latest version of TAB and have the bug again/still have it. Or did I misunderstand something?

**Comment by Tanguygab** [comment] 2024-03-30 13:43
You are using TAB 4.1.2, that's the latest release, not the latest dev build.
Download the latest dev build from the Actions tab

**Comment by NEZNAMY** [comment] 2024-03-30 13:43
That's right - latest **build**, from [actions](https://github.com/NEZNAMY/TAB/actions), not the latest **release**. The issue also received "4.1.3" milestone  and you are using 4.1.2.

**Comment by Lion-King287** [comment] 2024-03-30 13:45
Oh, I am so sorry - thank you for the fast support!

**Comment by NEZNAMY** [comment] 2024-03-30 13:47
We didn't provide support, this is an issue tracker, not support.

**Comment by Melon-Oof** [comment] 2024-03-30 14:00
Do I open another issue or keep it all here, I have the same/similiar issue both on latest release and dev build

**Comment by NEZNAMY** [comment] 2024-03-30 14:03
This issue was fixed, which means any issue you have is a different one. Open a new issue with full details.

**Closed** 2024-04-12 13:18 UTC
Labels: Type: Bug, Duplicate, Resolution: Added / Fixed
