### ISSUE TITLE
Tab doesn't refresh on server change

### ISSUE THREAD

**Issue by SwartZCoding** [NEZNAMY/TAB#613] opened 2022-06-10 09:02 UTC
### Server version

Purpur 1.18.1

### TAB version

Bridge : 2.0.2 & Bungee : 3.1.1

### Describe the bug

When a player switches from server 1 to server 2, the scoreboard stays on server 1. I haven't changed my configuration since. I just updated the Bridges to the latest version.

### Expected behavior

He supposed to replace by scoreboard server 2 ^^.

### Steps to reproduce

Install tab 3.1.1 on bungee.
Install Tab-Bridge 2.0.2 on spigot.

Try to 

### Additional info

My config : 

https://www.toptal.com/developers/hastebin/mupozaruca.pl

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment] 2022-06-10 09:16
Could you make an easier example configuration with just 2 scoreboards?

**Comment by NEZNAMY** [comment] 2022-06-10 09:29
Joining to lobby
![image](https://user-images.githubusercontent.com/6338394/173036007-b9a964cd-3c9f-4e48-8d6b-82cbe5891723.png)
/server minage
![image](https://user-images.githubusercontent.com/6338394/173036050-fb977e37-0b20-4ed9-b958-2b7814f6644f.png)

**Comment by SwartZCoding** [comment] 2022-06-10 09:33
> 

On lobby : https://gyazo.com/ad175df6736cc8ebbd34e9e68a28859f
On minage : https://gyazo.com/7b443a7851ad4e64f276de160a8c4556

I need to /sb 2 times to refresh correctly the scoreboard to have the correct one : https://gyazo.com/40f09252708c6f7a18d5a73ea9802b88

**Comment by NEZNAMY** [comment] 2022-06-10 09:34
Try latest build from actions (https://github.com/NEZNAMY/TAB/actions/runs/2471207338), which is what I am using.

**Comment by NEZNAMY** [comment] 2022-06-10 09:36
You can also set up a test network and try it there, which is what I am doing and anyone trying to provide working steps to reproduce should as well.

**Comment by SwartZCoding** [comment] 2022-06-10 22:23
> You can also set up a test network and try it there, which is what I am doing and anyone trying to provide working steps to reproduce should as well.

With this version, it's seems to work after a network reboot. Keep open this issue. I'm gonna check it for 2-3 days. Because last time i got this issue after some days.

**Comment by SwartZCoding** [comment] 2022-06-15 09:52
Seems to be fixed. However sometimes after a reboot on a specific server. Tab doesn't continue to refresh the placeholders on the scoreboard. I need to re-restart again the server to fix this issue.

**Comment by NEZNAMY** [comment] 2022-06-15 10:15
Need more info on that.

**Comment by Caleston** [comment] 2022-06-22 02:36
> Seems to be fixed. However sometimes after a reboot on a specific server. Tab doesn't continue to refresh the placeholders on the scoreboard. I need to re-restart again the server to fix this issue.

I'm having this issue too, our placeholders work at first but then just cease to update. Yet, this only happens on one server in the network while others continue to update normally. Probably should open a new ticket on this tho.

**Comment by NEZNAMY** [comment] 2022-06-22 09:40
You probably didn't install bridge there.

**Comment by Caleston** [comment] 2022-06-22 14:44
> 

It has TAB-Bridge v2.0.3, same as the other servers. Its quite confusing because the TAB config is the same on Waterfall, PAPI version, config and expansions are the same, but the other servers constantly update placeholders, while on this one server it works after a restart, but then it stops updating again, usually after switching servers.

**Comment by NEZNAMY** [comment] 2022-06-23 17:07
Need steps to reproduce.

**Comment by Caleston** [comment] 2022-07-08 00:52
> Need steps to reproduce.

I believe ours is a different issue. It seems that our nickname plugin (MultiChat) is forcefully overriding the tablist when the nickname is refreshed after a chat message gets sent. Tag seems to function normally and Tab works at first until it is refreshed and then other placeholders get wiped out.

**Comment by SwartZCoding** [comment] 2022-07-15 10:29
> Any news @SwartZCoding ?

I don't use MultiChat plugin, and i have the issue too.  I don't have any news sorry.

**Comment by NEZNAMY** [comment] 2022-07-15 10:31
Does scoreboard still not change on server switch? Are you able to reproduce it on a test network with only TAB?

**Comment by Caleston** [comment] 2022-07-15 18:07
In our case, it is each of our servers that has the issue where placeholders are removed once a nickname is applied.
The interesting this is that this only happens on 'local server'. Players on other servers over the proxy have the correct placeholders and nickname, even if it is actually showing it wrong for themselves. /btab reload fixes it momentarily.

Upon testing in a test network, there were no issues. Ran all the same plugins, same TAB settings and even used same live database for nicks and prefixes, but I never managed to get the tab/placeholders to break. It is really puzzling.

This issue for us started upon updating TAB, but we leaped over quite a few versions so I am unsure at which stage it would have been broken. We are still running 1.17.1 Paper, if that makes a difference.
Should I assume the issue lies elsewhere or could TAB or TAB-Bridge still have an issue? Sorry if it is a different issue than the ticket.

**Comment by NEZNAMY** [comment] 2022-07-15 18:10
Probably caused by another plugin and yes, this is a different issue. Asking for help in issues of others only makes everything more complicated, most notably readability and tracking the original issue.

**Comment by SwartZCoding** [comment] 2022-07-16 10:29
> Does scoreboard still not change on server switch? Are you able to reproduce it on a test network with only TAB?

I don't think i can reproduce it now. But i see something weird. This issue came sometimes when a server which use TabBridge on a network crash. And if i reboot this same server. Sometimes scoreboard don't refresh anymore

**Comment by NEZNAMY** [comment] 2022-07-16 10:37
Send a crash log if server crashes.

**Comment by SwartZCoding** [comment] 2022-07-17 06:32
> Send a crash log if server crashes.

Is not a tab crash. It's like for any crash. If your server shutdown randomly for any reasons. Sometimes he break the refresh

**Comment by NEZNAMY** [comment] 2022-07-17 09:42
So when server shuts down, starts again and you connect to it, placeholders don't work?

**Comment by SwartZCoding** [comment] 2022-07-17 21:58
> So when server shuts down, starts again and you connect to it, placeholders don't work?

Yes but only sometimes & not when he shutdown basically, specifically when he crash.

**Comment by NEZNAMY** [comment] 2022-07-18 11:25
Do internal placeholders refresh correctly at that time? Does /btab reload fix it? What does /btab cpu say?

**Comment by NEZNAMY** [comment] 2022-07-19 11:31
Did you get errors.log file in TAB folder?

**Comment by NEZNAMY** [comment] 2022-08-08 18:57
Any news @SwartZCoding ?

**Comment by SwartZCoding** [comment] 2022-08-09 15:58
> Any news @SwartZCoding ?

Hi ! Sorry for the delay. You can find here my errors.logs file of my Bungeecord side.

https://pastebin.com/Z2YuBsAh

Important Note : I had never clear this file since the start of my production mode to the end.

**Comment by NEZNAMY** [comment] 2022-08-09 16:17
You are outdated. Old TAB version does not support 1.19+ bungeecord as it changed internals.

**Comment by SwartZCoding** [comment] 2022-08-09 20:07
> You are outdated. Old TAB version does not support 1.19+ bungeecord as it changed internals.

At this moment, is it the latest. And it's running on 1.18 server not 1.19

**Comment by NEZNAMY** [comment] 2022-08-09 21:06
1.18 server? Is it no longer on bungeecord?

**Comment by SwartZCoding** [comment] 2022-08-10 08:26
> 1.18 server? Is it no longer on bungeecord?

FlameCord & 1.18 purpur work correctly. Now my server is not open so i don't have any others logs to help you. sry.

**Comment by NEZNAMY** [comment] 2022-08-10 08:30
Do you still have the issue though?

**Comment by NEZNAMY** [comment] 2022-08-15 13:36
@SwartZCoding can we make a progress on this?

**Comment by SwartZCoding** [comment] 2022-08-15 22:04
> @SwartZCoding can we make a progress on this?

Me, no because my server is down atm. Maybe someone else can give more inforamtions about this issue ^^.

**Comment by NEZNAMY** [comment] 2022-08-15 22:13
You appear to be the only one with this issue. Can we close this? If anyone else gets it, they can open a new one.

**Comment by SwartZCoding** [comment] 2022-08-16 07:20
> You appear to be the only one with this issue. Can we close this? If anyone else gets it, they can open a new one.

Sure.

**Closed** 2022-08-16 09:24 UTC
Labels: Bug, Unable to reproduce
