### ISSUE TITLE
Tag on Bungee network

### ISSUE THREAD

**Issue by thomaboehi** [NEZNAMY/TAB#776] opened 2022-12-30 00:10 UTC
### Server version

Paper 1.19.3

### TAB version

3.2.1

### Stack trace

29.12.2022 - 16:15:04 - [TAB v3.2.0] Failed to enable. Did you just invent a new way to break the plugin by misconfiguring it?
29.12.2022 - 16:15:04 - java.lang.ClassCastException: class java.util.ArrayList cannot be cast to class java.lang.String (java.util.ArrayList and java.lang.String are in module java.base of loader 'bootstrap')
29.12.2022 - 16:15:04 - 	at me.neznamy.tab.shared.features.scoreboard.ScoreboardManagerImpl.<init>(ScoreboardManagerImpl.java:67)
29.12.2022 - 16:15:04 - 	at me.neznamy.tab.shared.TAB.loadUniversalFeatures(TAB.java:230)
29.12.2022 - 16:15:04 - 	at me.neznamy.tab.shared.proxy.ProxyPlatform.loadFeatures(ProxyPlatform.java:117)
29.12.2022 - 16:15:04 - 	at me.neznamy.tab.platforms.bungeecord.BungeePlatform.loadFeatures(BungeePlatform.java:29)
29.12.2022 - 16:15:04 - 	at me.neznamy.tab.shared.TAB.load(TAB.java:157)
29.12.2022 - 16:15:04 - 	at me.neznamy.tab.shared.command.ReloadCommand.execute(ReloadCommand.java:22)
29.12.2022 - 16:15:04 - 	at me.neznamy.tab.shared.command.TabCommand.execute(TabCommand.java:55)
29.12.2022 - 16:15:04 - 	at me.neznamy.tab.platforms.bungeecord.Main$BTABCommand.execute(Main.java:86)
29.12.2022 - 16:15:04 - 	at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:212)
29.12.2022 - 16:15:04 - 	at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:163)
29.12.2022 - 16:15:04 - 	at io.github.waterfallmc.waterfall.console.WaterfallConsole.runCommand(WaterfallConsole.java:30)
29.12.2022 - 16:15:04 - 	at net.minecrell.terminalconsole.SimpleTerminalConsole.processInput(SimpleTerminalConsole.java:87)
29.12.2022 - 16:15:04 - 	at net.minecrell.terminalconsole.SimpleTerminalConsole.readCommands(SimpleTerminalConsole.java:181)
29.12.2022 - 16:15:04 - 	at net.minecrell.terminalconsole.SimpleTerminalConsole.start(SimpleTerminalConsole.java:143)
29.12.2022 - 16:15:04 - 	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:72)
29.12.2022 - 16:15:04 - 	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

### Additional info

Player TAG doesn't change on servers. It is always player's name, nothing else. 

Config:
Proxy TAB 3.2.1
Server1 TAB-Bridge
Server2 TAB-Bridge

Proxy Plugin list
`TAB, Plan, Protocolize, Pl-Hide-Pro, PixelMOTD, LuckPerms-Bungee, MapModCompanion, BungeeJoinMessages, CMIB, BungeeSafeguard`

Server1 Plugin list
`AdvancedDiscordLogger*, AzLink, CMI, CMILib, CoreProtect, CreativeManager, DiscordSRV, dynmap, LuckPerms, MapModCompanion, NoMobGriefing, OreAnnouncer, PlaceholderAPI, Plan, ProtocolLib, REGRandomizer, TAB-Bridge, Vault, voicechat, Votifier, VotingPlugin`

Server2 Plugin list
`CMI, CMILib, DiscordSRV, dynmap, FastAsyncVoxelSniper, FastAsyncWorldEdit (WorldEdit), goBrush, goPaint, HeadDatabase, LuckPerms, MapModCompanion, PlaceholderAPI, Plan, Plot2Dynmap, PlotSquared, ProtocolLib, spark, TAB-Bridge, Vault, voicechat, WorldEditSelectionVisualizer`

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [ ] I ticked all of the boxes without actually reading them
- [x] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by thomaboehi** [comment] 2022-12-30 00:12
Sorry this is a bug not an error.

**Comment by Tanguygab** [comment] 2022-12-30 00:18
nope, this is a misconfiguration error, something is supposed to be a string, yet you made it a list.
Send your config.yml to make sure

**Comment by Tanguygab** [comment] 2022-12-30 00:20
Closing since the issue is being dealt with on Discord

**Closed** 2022-12-30 00:21 UTC
Labels: Error
