### ISSUE TITLE
Placeholder from Scoreboard Objective (%objective_score_Deaths%) does not shown after reconnect

### ISSUE THREAD

**Issue by PatiTati** [NEZNAMY/TAB#459] opened 2021-12-26 09:35 UTC
I have setup an Scoreboard Objective for Death Counter. The counter for deaths are shown as placeholder %objective_score_Deaths% in Yellow Number. But if i reconnect the value is everytime 0. After /tab reload the right number of the Scoreboard Objective are shown.

Version Server: This server is running Paper version git-Paper-101 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 464b171)
You are running the latest version

Version TAB: 3.0.1

**Comment by NEZNAMY** [comment] 2021-12-26 12:15
Duplicate of #447, which will be fixed in the next version.

**Closed** 2022-01-31 17:22 UTC
Labels: Bug, Duplicate
