### ISSUE TITLE
Bug on 'prevent-spectator-effect'

### ISSUE THREAD

**Issue by MaksyKun** [NEZNAMY/TAB#912] opened 2023-06-04 18:48 UTC
### Server version

Waterfall - 1.19-R0.1-SNAPSHOT:3df3a27:526

### TAB version

3.3.2

### Describe the bug

Using the 
`prevent-spectator-effect.enabled: true`
value works fine if both the spectator and common player are in the same world. However once the spectator moves to another world through the proxy, common players start to see the name on the bottom of the tablist again.

As for as I know, we enabled this fix in 1.19.3. The bug occurs since the 1.19.4 update. Also, I realized that it happens most of the time, but not always.

### Expected behavior

It should supress the spectator names of spectators which are on an other server instance.

### Steps to reproduce

1 - Have a player change his gamemode to spectator (doesnt matter if its node1, node2, ...)
2 - Review the tablist as a player in survival-mode
3 - See the transparent name

(4 - Get back to the same node as the reviewing player and it shall be supressed again)

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Tanguygab** [comment] 2023-06-04 18:49
duplicate of #879

**Closed by Tanguygab** 2023-06-04 18:49 UTC
Labels: Type: Bug
