### ISSUE TITLE
The player is no longer there, but his nickname remains, do you know what might be happening and why

### ISSUE THREAD

**Issue by piterunioszefuncio** [NEZNAMY/TAB#1264] opened 2024-04-04 21:42 UTC
### Server version

1.18.2

### TAB version

TAB-4.1.3-SNAPSHOT

### Describe the bug

![obraz_2024-04-04_233748095](https://github.com/NEZNAMY/TAB/assets/165900707/63de2746-3161-4fec-b7e9-8dae027af91d)
![image](https://github.com/NEZNAMY/TAB/assets/165900707/f00dca0c-18bb-4b78-ac00-94c11a9abcfb)
The player is no longer there, but his name is still visible. When I go away and come back, his nickname will no longer be visible.

### Expected behavior

I don't use bungeecord. I use the itemsadder plugin for photos

### Steps to reproduce

I have no idea if it's the itemssader's fault? Don't put photos there or anything??

### Additional info

I wrote on discord but you sent me here.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment] 2024-04-04 22:05
Sounds like a duplicate of #1247 to me.

**Closed** 2024-04-21 08:57 UTC
Labels: Type: Bug, Duplicate
