### ISSUE TITLE
players showing up twice in the tablist

### ISSUE THREAD

**Issue by Keithsguest** [NEZNAMY/TAB#1145] opened 2023-11-15 14:12 UTC
### Server version

Paper 1.20.2

### TAB version

4.0.9

### Describe the bug

![image](https://github.com/NEZNAMY/TAB/assets/108156513/13110068-16ae-40a6-ad98-d4f6c56f838d)
so it seems that everything in the plugin is working except for the fact i can see me pop up twice in the tablist,
this shouldnt be an issue with compatibility with other plugins as the only other plugin that could effect this has their tablist feature disabled.

### Expected behavior

i should only show up once in the tablist and im showing up twice

### Steps to reproduce

i unsure of how to reproduce but i can send my config file over to see if thats the issue

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment] 2023-11-15 15:48
Send your config.yml

**Comment by Keithsguest** [comment] 2023-11-15 22:20
[config(1).txt](https://github.com/NEZNAMY/TAB/files/13370150/config.1.txt)
sent as a txt it wont let me attach .yml for some reason

**Comment by NEZNAMY** [comment] 2023-11-16 12:44
Does `/teams list` have any? Can you try with no other plugins?

**Comment by Keithsguest** [comment] 2023-11-16 13:23
i tried with no other plugins and that seemed to fix the issue, i try building it back plugin by plugin to see what the conflict is
it wasent happening for a few weeks, i updated all of essentials and added vault and since then it was broken might be a conflict between them either way thought i should bring it up so you're aware of it

**Comment by Keithsguest** [comment] 2023-11-16 13:43
ive been building back up and the conflict is somehwere in essentials so ill take a look at which of essentials plugins it is

**Comment by Keithsguest** [comment] 2023-11-17 00:25
found the issue its with a plugin called deluxehub so ill tweak my settings and see if it fixes anything

**Comment by NEZNAMY** [comment] 2023-11-17 09:27
Can you send link? Does it happen with its default config?

**Comment by Keithsguest** [comment] 2023-11-18 02:15
hey the plugin conflict is actually just between luckyperms and tab im wondering what im doing incorrectly with my groups names, sending over configs now 
[pebblehost-605138-xauob1.zip](https://github.com/NEZNAMY/TAB/files/13398702/pebblehost-605138-xauob1.zip)

**Comment by Keithsguest** [comment] 2023-11-18 02:16
![image](https://github.com/NEZNAMY/TAB/assets/108156513/673d27f4-a314-4b0b-920d-29a26cdabaa5)
![image](https://github.com/NEZNAMY/TAB/assets/108156513/8b84e645-0eec-4ed6-9157-34808775fc4b)
i thought i have them all in there properly but i could be wrong.

**Comment by NEZNAMY** [comment] 2023-11-18 10:29
LuckPerms does not affect this. Check if the player has correct nametag prefix, it looks like teams are failing to apply.

**Comment by Keithsguest** [comment] 2023-11-18 17:48
How would I do that?

**Comment by NEZNAMY** [comment] 2023-11-18 17:50
Using another player and looking at you in game.

**Comment by Keithsguest** [comment] 2023-11-18 22:46
![image](https://github.com/NEZNAMY/TAB/assets/108156513/bf1a965e-af81-4aa0-8c91-fb21be9c0172)
this is how it looks when i see another player, i checked from the other account and there was no prefix or anything by my name, also when the scoreboard tries to ping the other two bungeecord servers they show up as offline even though theres another player connected to them 
![image](https://github.com/NEZNAMY/TAB/assets/108156513/8baac04b-77d0-4913-ae36-a9d45b287696)
and when you connect to the two servers that are bungeecorded together you can see that they are both online but the lobby shows up as offline 
![image](https://github.com/NEZNAMY/TAB/assets/108156513/7058e928-337a-4f6a-9720-7a929a54b5be)

**Comment by Keithsguest** [comment] 2023-11-18 22:55
oh and for some reason when me and the alt account are on different multiverse worlds the other account doesnt show up on the tab twice but i still do

**Comment by Keithsguest** [comment] 2023-11-18 23:01
bro even more weirdness, take a look at this on my computer its fixed for no reason 
![image](https://github.com/NEZNAMY/TAB/assets/108156513/e232e3ca-6a24-41b5-9546-318d5504da83)
but from the alt account its broken still and they cant see my prefix but i can see theres on my screen and its not broken, im going to try with absolutely no client side mods cause at this point thats the only option i can thinks thats effecting it like this unless its due to the permissions the default rank has compared to OP but ill try the first option and let you know

**Comment by Keithsguest** [comment] 2023-11-18 23:10
maan this is getting even weirder for some reason when i have no mods installed it stops working on both ends 
![image](https://github.com/NEZNAMY/TAB/assets/108156513/e280544f-ef46-438b-8efd-6fa6660576f4)

whats your discord? at this point it might be a little easier to solve with a more dirrect form of contact

**Comment by NEZNAMY** [comment] 2023-11-19 08:53
My discord username is `neznamy` (keep in mind it's only for discussing bugs, not for support).

**Comment by NEZNAMY** [comment] 2023-11-22 18:05
Turned out to be a duplicate of #1135 as well as wrong installation (on  both proxy and backend).

**Closed by NEZNAMY** 2023-11-22 18:05 UTC
Labels: Type: Bug
