### ISSUE TITLE
Vanilla Nametag bug

### ISSUE THREAD

**Issue by Coder-TheSid** [NEZNAMY/TAB#532] opened 2022-03-16 18:49 UTC
### Server version

Purpur 1.17.1

### TAB version

3.1.0

### Describe the bug

Under custom nametag it writes vanilla nametag
 i already tryed invisible-nametags but its not working

### Expected behavior

The config.yml only  unlimited-nametag-mode enabled

group.yml:
yonetici:
  tabprefix: '%img_stafffounder% &7» &c'
  tagprefix: '%img_stafffounder% &7» &c'
admin:
  tabprefix: '%img_staffadmin% &7» &c '
  tagprefix: '%img_staffadmin% &7» &c '
moderator:
  tabprefix: '%img_staffmoderator% &7» &b '
  tagprefix: '%img_staffmoderator% &7» &b '
helper:
  tabprefix: '%img_staffhelper% &7» &a '
  tagprefix: '%img_staffhelper% &7» &a '  
_DEFAULT_:
  tabprefix: '%img_player% &7» &7'
  tagprefix: '%img_player% &7» &7'
  tabsuffix: '%afk%'
  tagsuffix: '%afk%'
  customtabname: '%essentialsnick%'
  customtagname: '%essentialsnick%'
  abovename: "&e%townychat_town%"
  belowname: "&6%townychat_nation%"

### Steps to reproduce

there is no settings 

### Additional info

no

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment] 2022-03-16 18:57
Screenshot? Output of `/tab debug <player>`?

**Comment by Coder-TheSid** [comment] 2022-03-16 18:59
![2022-03-16_21 59 22](https://user-images.githubusercontent.com/74655120/158666655-b4ef598a-b1bf-45bd-8a05-ffa945e32306.png)

**Comment by Coder-TheSid** [comment] 2022-03-16 19:42
Plugins (55): AntiNetherRoof, BetterRTP, Cannons, ChatColor2, Chunky, Citizens, CombatLogX, CoreProtect, DeluxeMenus, dynmap, Dynmap-Towny, EcoPower, eGlow, EnchantCrystals, EpicReplant, Essentials, EssentialsChat, EssentialsSpawn, ExoticGarden, FlagWar, GappleCooldown, GSit, HolographicDisplays, HolographicExtension, ItemsAdder, JumpPads, LiteBans, LiteXpansion, LoneLibs, LuckPerms, Movecraft, Multiverse-Core, NBTAPI, ObsidianDestroyer, PlaceholderAPI, PlugMan, ProtocolLib, QuickShop, Scoreboard-revision, SiegeWar, SirBlobmanCore (SirBlobmanAPI, XSeries), SkinsRestorer, Skript, Slimefun, TAB, Towny, TownyChat, TownyFlight, TownyResources, Vault, ViaBackwards, ViaVersion, Vulcan, WorldEdit, WorldGuard

**Comment by NEZNAMY** [comment] 2022-03-16 19:43
I am unable to fix this bug in an outdated eGlow version by changing TAB's code. Auto-updating other plugins is out of scope of the plugin's functionality.

**Comment by Coder-TheSid** [comment] 2022-03-16 19:44
Sorry i dont understand

**Comment by NEZNAMY** [comment] 2022-03-16 19:44
Update eGlow.

**Comment by Coder-TheSid** [comment] 2022-03-16 19:45
Ok

**Comment by Coder-TheSid** [comment] 2022-03-16 19:47
i was wondering what does eglow have to do with TAB?

**Comment by NEZNAMY** [comment] 2022-03-16 19:48
It manages teams, just like TAB does, to secure glow color. You can learn more about teams to find out.

**Comment by Coder-TheSid** [comment] 2022-03-16 19:48
Oh ok

**Comment by UltraFaceguy** [comment] 2022-03-17 01:18
Actually, seeing this as well. Latest paper 1.18.2, TAB 3.1.0

I don't have a glow plugin, and the only thing I can think of being relevant is libsdisguises... but that's set to latest. Intesetingly, it seems to always happen for some people, and never for others. I'm not using anything that should use teams for anything, and was using a very similar setup, this only appeared in 3.1.0

```
[TAB]: §3[TAB] §a§lShowing debug information
[TAB]: §7§m>-------------------------------<
[TAB]: §6Server version: §b1.18.2 (v1_18_R2)
[TAB]: §6Plugin version: §b3.1.0
[TAB]: §6Permission plugin: §bLuckPerms
[TAB]: §6Permission group choice logic: §bPrimary group
[TAB]: §6Sorting system: §bGROUPS then PLACEHOLDER_A_TO_Z
[TAB]: §7§m>-------------------------------<
[TAB]: §ePlayer: §a[De4dlocker]()
[TAB]: §ePrimary permission group: §adefault
[TAB]: §eTeam name: §a6De4dlockerA
[TAB]: §eTeam name note: §rPrimary group is #6 in sorting list. §r%player% returned "De4dlocker". §r
[TAB]: §atabprefix: §e"§r%titbadge_badge_icon%&f§r§e" §7(24) §7(Source: group=_DEFAULT_)
[TAB]: §atabsuffix: §e"§r%rel_strife_guild_rel_color%%strife_gTag_suffix%§r§e" §7(48) §7(Source: group=_DEFAULT_)
[TAB]: §acustomtabname: §e"§r%rel_strife_party_color%%player_name%&f%strife_afk%§r§e" §7(51) §7(Source: group=_DEFAULT_)
[TAB]: §atagprefix: §e"§r%rel_strife_guild_rel_color%%rel_strife_party_color%%strife_gTag_prefix%%strife_glow%%rel_strife_party_color%§r§e" §7(109) §7(Source: group=_DEFAULT_)
[TAB]: §atagsuffix: §e"§r &7%rel_strife_party_color%Lv%player_level%§r§e" §7(43) §7(Source: group=_DEFAULT_)
[TAB]: §aabovename: §e"§r%strife_level_color%%luckperms_prefix%%titbadge_badge%%strife_level_color%%luckperms_prefix%%titbadge_title%§r§e" §7(108) §7(Source: group=_DEFAULT_)
[TAB]: §abelowname: §e"§r§r§e" §7(0) §7(Source: None)
[TAB]: §aanother: §e"§r§r§e" §7(0) §7(Source: None)
[TAB]: §amyCustomLine: §e"§r§r§e" §7(0) §7(Source: None)
[TAB]: §acustomtagname: §e"§r&f%rel_strife_party_color%%player_name%&f%strife_afk%§r§e" §7(53) §7(Source: group=_DEFAULT_)
[TAB]: §7§m>-------------------------------<
```

`Plugins (87): AddFlags, AdvancedPortals, ArmorStandEditor, Battered, BlockRegenerator, BossShopPro, BowSecurity, Bullion, Cartographer2, Celeste, Citizens, CMILib, CommandSigns, Containers, CraftingStore, CrateReloaded, DecentHolograms, DeluxeInvy, DiscordSRV, Disposal, EasyBackup, EasyBackupCore, EconomyRepair, EmojiSpam, EpicMounts, EzChat, Facecore, FacelandMarket, FacePet, FaceQuest, FastAsyncWorldEdit (WorldEdit), ForceResourcepacks (WorldResourcepacks), GigaVote, GUIAPI, Guilds, HeadDatabase, InteractiveBooks, InteractiveChat, InteractiveChatDiscordSrvAddon, ItemEdit, Jobbo, LibsDisguises, LightCleaner, LiteBans, Loot, LuckPerms, MiniInvyGui, MiniMOTD, ModelEngine, MoreFish, Multiverse-Core, OpenInv, Outpost, PacketListenerApi, PartyRoom, PlaceholderAPI, PlayerParticles, PlayerPoints, PlugMan, ProtocolLib, RandomizedTrades, RecipeManager, RPGFoodsAndHealth, Shop, skRayFall, Skript, skript-placeholders*, SnazzyFarming, SnazzyParties, SoundBox, spark, Storinator9000, Strife, StrifeArena, SuperSeatBoi, TAB, TitsAndBadge, TogglePickups, TradeMe, Vault, VoidGen, Votifier, Waypointer, WeekStreak, WorldBorderAPI, WorldGuard, YouCannotHandleMyPotions`

![2022-03-16_21 15 00](https://user-images.githubusercontent.com/1491435/158717432-1cafc16a-32b4-4edc-8552-b31a00bffd9f.png)

**Comment by UltraFaceguy** [comment] 2022-03-17 03:10
I've discovered more info on it... It seems as if this vanilla nameplate shows only for people ABOVE you in the scoreboard. Relogging resorts the board (even though people should be ordered based on permission on my server) and players who get put above you display the double nametag, as seen below. Also, it seems like the extra nameplate is formatted as LIGHT_GRAY, which is interesting, it doesn't seem to be the vanilla nameplate!

![2022-03-16_23 06 25](https://user-images.githubusercontent.com/1491435/158728755-f9bee1f9-a3e5-483a-b4a2-6441279c4531.png)

**Comment by NEZNAMY** [comment] 2022-03-17 07:33
Maybe broken protocollib, try downgrading / removing it, you are currently duplicating #527

**Comment by Coder-TheSid** [comment] 2022-03-17 16:57
the problem fixed but some of group config's not working eg. _DEFAULT_ group's tagprefix working but yonetici not

**Comment by NEZNAMY** [comment] 2022-03-17 16:57
Probably because you did not configure weights in luckperms. Group settings work.

**Comment by Coder-TheSid** [comment] 2022-03-17 16:58
![image](https://user-images.githubusercontent.com/74655120/158853728-3b8c7d7b-7813-4d02-b89c-af6fba3d395f.png)

**Comment by NEZNAMY** [comment] 2022-03-17 17:00
Debug command will tell you why and so will the wiki.

**Comment by Coder-TheSid** [comment] 2022-03-17 17:03
the kurucu group already added in my perm list at luckperms

**Comment by NEZNAMY** [comment] 2022-03-17 17:05
Because you are owner, obviously.

**Comment by Coder-TheSid** [comment] 2022-03-17 17:06
wdym

**Comment by NEZNAMY** [comment] 2022-03-17 17:08
The screenshot you sent very clearly says you are owner.

**Comment by Coder-TheSid** [comment] 2022-03-17 17:12
I changed the config but still same

**Comment by Coder-TheSid** [comment] 2022-03-17 17:14
![2022-03-17_20 13 47](https://user-images.githubusercontent.com/74655120/158856709-1e279bdc-47d2-49ef-8cf6-ae947eb4892d.png)

**Comment by Coder-TheSid** [comment] 2022-03-17 18:32
I update my Procotollib too

**Comment by NEZNAMY** [comment] 2022-03-17 18:33
Screenshot? Config?

**Comment by NEZNAMY** [comment] 2022-04-01 08:37
Looks like this is caused by broken ProtocolLib version, closing due to inactivity from user.

**Closed by NEZNAMY** 2022-04-01 08:37 UTC
Labels: Bug, Invalid
