### ISSUE TITLE
Sorting players in tablist on multiservers

### ISSUE THREAD

**Issue by corrysamu** [NEZNAMY/TAB#1155] opened 2023-11-25 09:38 UTC
### Server version

Waterfall 1.20.2

### TAB version

4.0.6

### Describe the bug

Hi, I have a problem, I noticed that it is not possible to do permission groups for servers

Example sorting:
**Sorting Server1**: Group1, Group2, Group3
**Sorting Server2**: Group4, Group,1, Group3

Can I set a different order for each server?

### Expected behavior

Sorting Server1: Group1, Group2, Group3
Sorting Server2: Group4, Group,1, Group3

### Steps to reproduce

Connect multiple servers to plugin tab on bungeecord and put configure groups

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment] 2023-11-25 09:51
* Not a bug, plugin doesn't offer per-server sorting types
* 
![image](https://github.com/NEZNAMY/TAB/assets/6338394/28e03565-2e1d-4835-b577-95e0ca80c715)
* Where is 4.0.6 latest?

**Comment by corrysamu** [comment] 2023-11-25 10:01
Mine was simply a question, vito that you do not offer a space for questions I was forced to open a bug report

**Comment by NEZNAMY** [comment] 2023-11-25 10:03
Correct, support services are no longer provided, see readme for more info.

**Comment by corrysamu** [comment] 2023-11-25 10:06
I need this features, I can also pay you, would you give me a quote? and if it is possible we can write about discord?

**Comment by NEZNAMY** [comment] 2023-11-25 10:07
Feature requests are closed as well and keep in mind that this is a [public plugin](https://github.com/NEZNAMY/TAB/wiki#public-plugin), meaning I will not be adding everything everyone can come up with as that would be impossible to manage.

**Comment by corrysamu** [comment] 2023-11-25 10:09
But what if I asked you for an addon using obviously paid bees?

**Comment by corrysamu** [comment] 2023-11-25 10:10
then if you want you can also put it on the various sales sites of pluign

**Comment by NEZNAMY** [comment] 2023-11-25 10:11
Assuming you don't want some sort of per-player sorting view, you can achieve this using conditions. However, I am no longer interested in configuring servers.

**Comment by corrysamu** [comment] 2023-11-25 10:15
I understand that you do not want to set up servers,  for a matter of time, but you could give me an example, it takes literally 2 seconds, you are the developer of the plugin and you know best of all how the plugin works

**Comment by NEZNAMY** [comment] 2023-11-25 10:20
It doesn't take 2 seconds. I don't know if I understood your request correctly, but what you can do is:
* Create one-frame animation for each server that only contains %group% and configure [replacements](https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Placeholder-output-replacements) and give each group a number from 1 to X
* Create a condition (for 3 and more servers 2 conditions) and check for server. If it's first server, show animation 1, if second server, animation 2
* Sort by [PLACEHOLDER_LOW_TO_HIGH](https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Sorting-players-in-tablist#placeholder_low_to_high) and use that condition as the placeholder.
  
I obviously haven't tested this and will not do it, however it should give you a good idea what to do.

**Comment by corrysamu** [comment] 2023-11-25 10:25
Ok thank you so much escusa for the trouble and I will try it

**Closed** 2023-11-27 16:26 UTC
Labels: Support is not provided in github issues
