### ISSUE TITLE
Players being kicked "Team 13I already exists in this scoreboard"

### ISSUE THREAD

**Issue by haeiven** [NEZNAMY/TAB#427] opened 2021-12-06 19:00 UTC
**Server version**
Paper 1.8.9

**Plugin version** ("latest" is not a version)
3.0.0

**Describe the bug**
Few players are randomly disconnected at the same time from the spigot server.

**Additional info** (errors, screenshots, ...)
Error on bungee: https://paste.soleria.eu/gosujezuhe.apache
Config: https://paste.soleria.eu/duzolizogu.yaml

This never happened on version 2.9.2 (Premium).

**Comment by Tanguygab** [comment] 2021-12-06 19:01
try to add `- "PLACEHOLDER_A_TO_Z:%player%"` below the GROUPS sorting type

**Comment by NEZNAMY** [comment] 2021-12-06 19:01
Duplicate of #422

**Closed** 2021-12-11 11:41 UTC
Labels: Duplicate
