### ISSUE TITLE
1.18.1 issue: Tag suffix & prefix in tab

### ISSUE THREAD

**Issue by div2005** [NEZNAMY/TAB#439] opened 2021-12-11 14:10 UTC
After 1.18.1 update there is an issue with player tab list. When player joins the server it displays other players with tag-prefix and tag suffix instead of tab-prefix and tab-suffix correspondingly.
Didn't saw this problem on 1.18. 

__Tested with default config__ and our's (in our confug other players must have suffix same as mine)
**Using Waterfall** (Bungeecord)
**Game version**: 1.18.1
**TAB version**: 3.0.1 
**TAB-Bridge vesion**: 1.6.0

![image](https://user-images.githubusercontent.com/46396764/145678624-772f1677-73d0-441a-9e7e-5a73b4e5625a.png)
![image](https://user-images.githubusercontent.com/46396764/145679409-1a87db24-f8b9-44e3-91a6-957501d1c591.png)

**Comment by NEZNAMY** [comment] 2021-12-11 14:11
https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Nametags#additional-note-1

**Comment by div2005** [comment] 2021-12-11 14:13
![image](https://user-images.githubusercontent.com/46396764/145679697-cb5ef7cb-f4be-4397-b0e8-b13a5fd159fc.png)

**Comment by NEZNAMY** [comment] 2021-12-11 14:14
You didn't even send your configuration, many things could have gone wrong.

**Comment by div2005** [comment] 2021-12-11 14:14
I have same problem with default config

**Comment by div2005** [comment] 2021-12-11 14:16
As i see by default this feature is enabled

**Comment by NEZNAMY** [comment] 2021-12-11 14:17
Can you try again if it's not present on 1.18?

**Comment by div2005** [comment] 2021-12-11 14:19
Sure, i'll do it now and send you video

**Comment by div2005** [comment] 2021-12-11 14:27
Same issue in all cases

Latest tab + MC 1.18.1.
https://www.youtube.com/watch?v=baZo1A9EBL8

Latest tab + MC 1.18
https://www.youtube.com/watch?v=FmxdPkHLqqk

Tab 3.0.0 + MC 1.18
https://www.youtube.com/watch?v=ytTxohZ9LCQ

**Comment by div2005** [comment] 2021-12-11 14:28
Can it be a bungee issue?

**Comment by NEZNAMY** [comment] 2021-12-11 14:29
Can you try with older bungeecord where you didn't have the issue? Does /btab reload fix it?

**Comment by div2005** [comment] 2021-12-11 14:32
/btab reload fix it, yep 
also when player switches a world fixes it

I'll try an older version now

**Comment by div2005** [comment] 2021-12-11 14:40
We didn't use bungee before there. We used your plugin on basic paper server and we don't how long this issue exicting

**Comment by div2005** [comment] 2021-12-11 14:40
It will be hard to try it with older versions

**Comment by NEZNAMY** [comment] 2021-12-17 13:33
You did not even send your config.

**Comment by div2005** [comment] 2021-12-17 13:37
Tested with default configuration ._.

**Comment by NEZNAMY** [comment] 2021-12-17 13:38
Still having the issue? Just install the plugin on bungeecord and join? That's all?

**Comment by div2005** [comment] 2021-12-17 13:39
Yes

**Comment by NEZNAMY** [comment] 2021-12-17 13:48
![image](https://user-images.githubusercontent.com/6338394/146553999-f174412d-a22c-4e86-9dd7-6906cef9b4bb.png)
I join and everything is fine. TAB 3.0.1 with default config.

**Comment by div2005** [comment] 2021-12-17 14:09
have you tested with few players and rejoins?

**Comment by NEZNAMY** [comment] 2021-12-17 14:12
I tested with 2 accounts and kept rejoining, yes.

**Comment by Thefirstalpha** [comment] 2022-01-03 20:26
Hello, I have the same issue using a velocity proxy, players appears sometimes in blank, after they join/quit the server, and also disappears sometimes, but a /btab reload fix the actual list of players.

Using TAB 3.0.1, issues was also in 3.0.0
Luckperms from 5.3.33 to 5.3.89

**Comment by NEZNAMY** [comment] 2022-01-03 20:27
That explains it, try bungeecord.

**Comment by Thefirstalpha** [comment] 2022-01-03 20:30
I would if I can, but our infrastructure is made on velocity ^^'

**Comment by NEZNAMY** [comment] 2022-01-03 20:30
Can you try on a some test server then?

**Comment by Pierrot-la-menace** [comment] 2022-01-13 22:41
Hello @NEZNAMY 

I'm in thefirstalpha's dev team. I have the same bug on a smaller infra on BungeeCord. It appears randomly when people are changing of server.
I will try to send you a capture !

**Comment by Pierrot-la-menace** [comment] 2022-01-13 22:44
Here is a another bug :
![image](https://user-images.githubusercontent.com/45047908/149420733-abda3a4c-ee87-447c-ad24-30fd410cb933.png)

**Comment by NEZNAMY** [comment] 2022-01-13 22:52
Steps to reproduce (and configuration files if not using default) would be even better.

**Comment by Pierrot-la-menace** [comment] 2022-01-13 23:26
Let me do that ;)

**Comment by NEZNAMY** [comment] 2022-01-14 09:38
Make sure to also use the latest build from actions first.

**Comment by Thefirstalpha** [comment] 2022-01-14 11:25
# Just another piece of information on velocity
TAB 3.0.1
Latest build of Velocity

![image](https://user-images.githubusercontent.com/25564305/149507031-d2c8fa8c-eb97-42cd-bc54-8639c3f309ae.png)

**A `/btab reload` fix the current visual issue temporarly**
![image](https://user-images.githubusercontent.com/25564305/149507395-9eb7dc6d-43d7-4ae0-8590-829af48018c9.png)

# config.yml :
```
scoreboard-teams:
  enabled: true
  invisible-nametags: false
  anti-override: true
  enable-collision: true
  sorting-types:
  - GROUPS:fondateur,administrateur,developpeur,moderateur,mentor,animateur,architecte,master,vip,citoyen,joueur,visiteur
  - PLACEHOLDER_A_TO_Z:%player%
  case-sensitive-sorting: true
  disable-in-worlds:
  - disabledworld
  disable-in-servers:
  - disabledserver
  unlimited-nametag-mode:
    enabled: false
    use-marker-tag-for-1-8-x-clients: false
    disable-on-boats: true
    space-between-lines: true
    disable-in-worlds:
    - disabledworld
    dynamic-lines:
    - abovename
    - nametag
    - belowname
    - another
    static-lines:
      myCustomLine: 0.66
tablist-name-formatting:
  enabled: true
  align-tabsuffix-on-the-right: false
  character-width-overrides: {}
  anti-override: true
  disable-in-worlds:
  - disabledworld
  disable-in-servers:
  - disabledserver
header-footer:
  enabled: true
  disable-in-worlds:
  - disabledworld
  disable-in-servers:
  - disabledServer
  header:
  - '&3&lDecaCraft'
  - '%time%'
  - '%date%'
  - '&7Connecté(s):&b %online%&r&7/&3%maxplayers%'
  - '&7Staff en ligne:&e %staffonline%'
  - ' &7-==================- '
  - '&7Ping:&a %ping%&7 ms'
  - ' &7-==================- '
  footer:
  - ' &7-==================- '
  - '%animation:discord%'
  - '&esite: %animation:web%'
  per-server: {}
yellow-number-in-tablist:
  enabled: true
  value: '%ping%'
  disable-in-worlds:
  - disabledworld
yellow-number:
  disable-in-servers:
  - disabledserver
belowname-objective:
  enabled: false
  number: '%ping%'
  text: Ping
  disable-in-worlds:
  - disabledworld
  disable-in-servers:
  - freebuild
prevent-spectator-effect:
  enabled: false
bossbar:
  enabled: false
  toggle-command: /bossbar
  remember-toggle-choice: false
  hidden-by-default: false
  default-bars:
  - ServerInfo
  disable-in-servers:
  - disabledserver
  bars: {}
scoreboard:
  enabled: true
  toggle-command: /sb
  remember-toggle-choice: false
  hidden-by-default: false
  use-numbers: false
  static-number: 0
  delay-on-join-milliseconds: 0
  disable-in-worlds:
  - disabledworld
  respect-other-plugins: true
  scoreboards: {}
ping-spoof:
  enabled: false
fix-pet-names:
  enabled: false
placeholders:
  date-format: '&7»&8 dd&7/&8MM&7/&8yyyy &7«'
  time-format: '&7»&8 HH&7:&8mm &7«'
  time-offset: 0
  remove-strings:
  - '[]'
  - < >
placeholder-output-replacements:
  '%essentials_vanished%':
    'yes': '&7| Vanished'
    'no': ''
  '%tps%':
    '20': '&aPerfect'
  '%afk%':
    'true': '&5[AFK] '
    'false': ''
conditions: {}
placeholderapi-refresh-intervals:
  default-refresh-interval: 100
  server:
    '%server_uptime%': 1000
    '%server_tps_1_colored%': 1000
  player:
    '%player_health%': 200
    '%player_ping%': 1000
    '%vault_prefix%': 1000
  relational:
    '%rel_factionsuuid_relation_color%': 500
assign-groups-by-permissions: false
primary-group-finding-list:
- fondateur
- administrateur
- developpeur
- moderateur
- mentor
- animateur
- architecte
- master
- vip
- joueur
- citoyen
- default
debug: false
mysql:
  enabled: false
  host: 127.0.0.1
  port: 3306
  database: tab
  username: user
  password: password
use-bukkit-permissions-manager: false
global-playerlist:
  enabled: true
  spy-servers:
  - freebuild
  - lobby
  - event
  - creatif
  display-others-as-spectators: false
  display-vanished-players-as-spectators: true
  isolate-unlisted-servers: false
  update-latency: false
use-online-uuid-in-tablist: true
```

**Comment by NEZNAMY** [comment] 2022-01-14 11:31
I tried your config and got this on join with TAB 3.0.1, your config and velocity build 109.
![image](https://user-images.githubusercontent.com/6338394/149508771-36990500-ade6-4e90-951a-05fdde330967.png)

**Comment by Thefirstalpha** [comment] 2022-01-17 11:09
The issue doesn't append everytime, most of the case, it's just after moving from one server to another, for the moment, the only solution that I've found is to /btab reload every 10 minutes

**Comment by NEZNAMY** [comment] 2022-01-18 10:24
Try latest build from https://github.com/NEZNAMY/TAB/actions, I increased event processing delay.

**Comment by NEZNAMY** [comment] 2022-01-31 18:00
Try 3.0.2

**Comment by Thefirstalpha** [comment] 2022-02-04 16:19
So after some testing, this new version look really better. In 3.0.1, we have like 5 blank people over 10 connected, in 3.0.2, we mainly have 0 people in blank. They was just appearing sometimes in blanc, like when they connected or when they switch from servers. Seeing that, I've take a look on how the tab really work from the side of mojang, bukkit, ...
I'have decide to create like my own tab plugins, to print message from packet, and I found what cause the blank people in the tab.
It appear when the packet send from TAB is send before the PackPlayerInfo from bukkit (like when a lag append for example), because the packet of bukkit is overrinding the change of color made by TAB. So I've simply made a drop of all packet send from bukkit (for PlayerInfo), and now everything is working fine !

The things is, velocity need a packet filter api, to drop or modify packet, if we want that TAB completly works on velocity without any dependencies on the server side.

**Comment by NEZNAMY** [comment] 2022-02-04 16:30
Any news @div2005 ?

**Comment by NEZNAMY** [comment] 2022-02-21 17:22
Can you show bungeecord plugin list @div2005 ?

**Comment by div2005** [comment] 2022-02-21 18:07
> Can you show bungeecord plugin list @div2005 ?

Cannot give you an answer, dont using bugeecord at the moment

**Comment by NEZNAMY** [comment] 2022-02-21 18:08
Does that mean this issue is no longer valid? If so, you can probably close it.

**Closed** 2022-02-21 20:56 UTC
Labels: Unable to reproduce

**Comment by nhanledev** [comment] 2022-11-08 04:11
the same thing happens on bungeecord/waterfall to me. All placeholders from PlaceholderAPI got reset when player switch server.
