### ISSUE TITLE
Can't see prefixes in the Tab

### ISSUE THREAD

**Issue by MrPepsikk** [NEZNAMY/TAB#1161] opened 2023-12-02 20:22 UTC
### Server version

Waterfall (latest version) & Spigot 1.8.8

### TAB version

4.0.9

### Describe the bug

I'm running plugin on BungeeCord (WaterFall latest version) and the plugin works as it should but when I use version 1.8.8 I cant see my prefix in tab and sorting does not work as well for me.
![image](https://github.com/NEZNAMY/TAB/assets/77855606/674c9486-6c09-40ad-99d2-e22bb37f56e4)

Also when I use command /btab debug it says error:
![image](https://github.com/NEZNAMY/TAB/assets/77855606/52c8b21b-06aa-4eb7-834b-ddd6514a79d6)

(Works) When I join the same server in BungeeCord but with version 1.20.2:
![image](https://github.com/NEZNAMY/TAB/assets/77855606/12cc0bfd-782d-496b-bb1a-cafd083b1af9)

### Expected behavior

Prefixes in tab dont work as expected when I use 1.8.8, but on version 1.20.2 it works great.

### Steps to reproduce

Fix bug with prefix visibility in version 1.8.8

### Additional info

I don't know for sure, but the problem can maybe cause plugin ViaVersion, but like I said I rather let solve this to someone who has more experience with this.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment] 2023-12-02 20:23
About a millionth duplicate of #1135

**Comment by MrPepsikk** [comment] 2023-12-02 20:25
Oh sorry didnt see, my bad. I had this problem for too long I couldnt fix it for at least 4 weeks.

**Comment by NEZNAMY** [comment] 2023-12-02 20:26
Sounds about right, that's date of the first API break of the 3 BungeeCord had in the past few weeks.

**Closed** 2023-12-02 20:44 UTC
Labels: Type: Bug, Resolution: Duplicate
